const prepLines=['BISE','MINERÍA','WALMART','FACILITY'],dispatchLines=['BISE','MINERÍA','WALMART','WALMART RM','FACILITY'];
const prep=[[600,400,67],[450,310,69],[700,520,74],[280,190,68]],dispatch=[[280,170,130,92],[210,140,98,75],[340,215,160,118],[0,0,0,0],[150,80,62,41]];
prepLines.splice(3,0,'WLM RM');prep.splice(3,0,[0,0,0]);dispatchLines[3]='WLM RM';
const shifts=[{id:'noche',label:'Turno noche',cuts:['01:00','03:00','05:00']},{id:'manana',label:'Turno mañana',cuts:['09:00','11:00','13:00']},{id:'tarde',label:'Turno tarde',cuts:['17:00','19:00','21:00']}],cuts=shifts.flatMap(shift=>shift.cuts);
document.querySelector('.heading span').textContent='Operación · CD Aramark';
const areaNames={recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'},roleNames={operativo:'operativo',grua:'grúa'};
const JSON_STORAGE_KEY='dhl-reuniones-diarias-json';
const HSE_STORAGE_KEY='dhl-hse-dias-sin-accidentes';
const PREVENTION_STORAGE_KEY='dhl-hse-indice-prevencion';
const QRA_STORAGE_KEY='dhl-qra-5s-persistente';
const CUSTOMER_AUDIT_STORAGE_KEY='dhl-auditoria-cliente';
const BUSINESS_LINES_STORAGE_KEY='dhl-lineas-negocio-visibles',businessLines=[...dispatchLines];
const NOTES_STORAGE_KEY='dhl-bloc-notas-persistente';
const controlIcon=name=>({
  list:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/></svg>',
  radar:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 3v18M3 12h18"/><circle cx="15" cy="9" r="1.5" class="icon-fill"/></svg>',
  filter:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M7 12h10M10 18h4"/></svg>',
  calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M8 14h2M14 14h2M8 18h2"/></svg>',
  gauge:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 18a8 8 0 1 1 16 0M12 18l5-7"/><circle cx="12" cy="18" r="1.5" class="icon-fill"/></svg>'
}[name]||'');
let selectedTransfer=null,lastMove=null,toastTimer=null,initialSnapshot=null,dailyRecord=null,dirty=false,activeDate='',selectedClearArea=null,activeSummaryArea='recepcion',activeInheritedFrom=null,refreshBusinessLineFilters=()=>{};
const activeTransfers=new Map();
const emptyExpectedKilos=()=>({in:'',out:''}),sanitizeExpectedKilos=value=>String(value??'').replace(/\D/g,'').slice(0,9).replace(/^0+(?=\d)/,''),formatExpectedKilos=value=>sanitizeExpectedKilos(value).replace(/\B(?=(\d{3})+(?!\d))/g,'.');
let expectedKilos=emptyExpectedKilos();
let persistentNotes={strokes:[],updatedAt:null},notesTool='pen',lastScreenshot=null,lastScreenshotUrl='',capturingView=false;
const activeNoteStrokes=new Map();
let crew={recepcion:{operativo:88,grua:20,planOperativo:92,planGrua:22},preparacion:{operativo:42,grua:12,planOperativo:45,planGrua:12},despacho:{operativo:31,grua:0,planOperativo:33,planGrua:0}};
let crewEntered={recepcion:{operativo:false,grua:false},preparacion:{operativo:false,grua:false},despacho:{operativo:false,grua:false}};
const emptyTransferBalance=()=>({recepcion:{operativo:0,grua:0},preparacion:{operativo:0,grua:0},despacho:{operativo:0,grua:0}});let transferBalance=emptyTransferBalance();
const areaSupportsRole=(area,role)=>role!=='grua'||area!=='despacho';
function normalizeDispatchCrew(){crew.despacho.grua=0;crew.despacho.planGrua=0;crewEntered.despacho.grua=false;if(transferBalance?.despacho)transferBalance.despacho.grua=0}
function settleTransfers(){Object.keys(crew).forEach(area=>['operativo','grua'].forEach(role=>crew[area][role]=Math.max(0,crew[area][role]-(transferBalance[area]?.[role]||0))));transferBalance=emptyTransferBalance()}

document.querySelector('#prepRows').innerHTML=prepLines.map((line,index)=>`<tr data-business-line="${line}"><td>${line}</td>${prep[index].map((value,column)=>`<td class="editable-cell ${column===2?'prep-advance':''}">${value}</td>`).join('')}</tr>`).join('');
document.querySelector('#dispatchRows').innerHTML=dispatchLines.map((line,index)=>`<tr data-business-line="${line}"><td>${line}</td>${dispatch[index].map(value=>`<td class="editable-cell">${value}</td>`).join('')}</tr>`).join('');
document.querySelector('#cutList').innerHTML=shifts.map((shift,shiftIndex)=>`<section class="shift-group ${shift.id}"><span>${shift.label}</span><div class="shift-times">${shift.cuts.map((cut,index)=>`<button type="button" class="cut-chip incomplete ${shiftIndex===0&&index===0?'active':''}" data-cut="${cut}">${cut}</button>`).join('')}</div></section>`).join('');

const personIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7 8.2c0-3.5-3.1-6.2-7-6.2s-7 2.7-7 6.2V22h14v-1.8Z"/></svg>';
function renderInlineCrew(){
  document.querySelectorAll('.dotacion').forEach((card,index)=>{
    const area=['recepcion','preparacion','despacho'][index],data=crew[area];card.dataset.area=area;
    const craneRole=areaSupportsRole(area,'grua')?`<div class="workforce-role" data-role="grua"><span>Grúas</span><div class="workforce-fields"><button class="workforce-numbers" data-field="grua" data-label="Grúas que asistieron"><small>Asistió</small><strong>${data.grua}</strong></button><button class="workforce-numbers" data-field="planGrua" data-label="Dotación total de grúas"><small>Total</small><strong>${data.planGrua}</strong></button></div><button class="person-handle" data-origin="${area}" data-role="grua" aria-label="Mover una grúa desde ${areaNames[area]}">${personIcon}</button></div>`:'';
    card.querySelector('.attendance').outerHTML=`<div class="inline-workforce${area==='despacho'?' single-workforce':''}">
      <div class="workforce-role" data-role="operativo"><span>Operativos</span><div class="workforce-fields"><button class="workforce-numbers" data-field="operativo" data-label="Operativos que asistieron"><small>Asistió</small><strong>${data.operativo}</strong></button><button class="workforce-numbers" data-field="planOperativo" data-label="Dotación total de operativos"><small>Total</small><strong>${data.planOperativo}</strong></button></div><button class="person-handle" data-origin="${area}" data-role="operativo" aria-label="Mover una persona operativa desde ${areaNames[area]}">${personIcon}</button></div>
      ${craneRole}
    </div>`;
  });document.querySelectorAll('.workforce-numbers').forEach(element=>element.addEventListener('click',openEditor));bindInlineCrew();
}
function updateTransferBadges(){document.querySelectorAll('.person-handle').forEach(button=>{let badge=button.querySelector('.transfer-balance');if(!badge){badge=document.createElement('small');badge.className='transfer-balance';button.append(badge)}const value=transferBalance[button.dataset.origin]?.[button.dataset.role]||0;badge.textContent=value>0?`+${value}`:value<0?String(value):'';badge.classList.toggle('positive',value>0);badge.classList.toggle('negative',value<0)})}
function updateInlineCounts(){document.querySelectorAll('.dotacion').forEach(card=>{const area=card.dataset.area;card.querySelectorAll('.workforce-numbers').forEach(field=>field.querySelector('strong').textContent=crew[area][field.dataset.field])});updateTransferBadges();refreshBusinessLineFilters()}
function clearDropState(){const dragging=[...activeTransfers.values()].filter(state=>state.dragging),canReceive=(state,area)=>state.origin!==area&&areaSupportsRole(area,state.role);document.body.classList.toggle('transfer-mode',dragging.length>0||Boolean(selectedTransfer));document.querySelectorAll('.dotacion').forEach(card=>{const area=card.dataset.area;card.classList.toggle('drop-ready',dragging.some(state=>canReceive(state,area))||Boolean(selectedTransfer&&canReceive(selectedTransfer,area)));card.classList.toggle('drop-hover',dragging.some(state=>state.hover===area&&canReceive(state,area)))});document.querySelectorAll('.person-handle').forEach(button=>button.classList.toggle('selected',selectedTransfer?.origin===button.dataset.origin&&selectedTransfer?.role===button.dataset.role));document.querySelector('#transferTip')?.classList.toggle('show',dragging.length>0||Boolean(selectedTransfer))}
function markDestinations(){clearDropState()}
function chooseTransfer(button){const sameSelection=selectedTransfer?.origin===button.dataset.origin&&selectedTransfer?.role===button.dataset.role;if(sameSelection){selectedTransfer=null;clearDropState();return}clearDropState();selectedTransfer={origin:button.dataset.origin,role:button.dataset.role};button.classList.add('selected');markDestinations(selectedTransfer.origin)}
function moveOne(origin,destination,role){
  if(!origin||!destination||origin===destination||!areaSupportsRole(origin,role)||!areaSupportsRole(destination,role)||crew[origin][role]<1)return;
  crew[origin][role]-=1;crew[destination][role]+=1;transferBalance[origin][role]-=1;transferBalance[destination][role]+=1;crewEntered[origin][role]=true;crewEntered[destination][role]=true;lastMove={origin,destination,role};selectedTransfer=null;clearDropState();updateInlineCounts();markDirty();
}
function bindInlineCrew(){
  document.querySelectorAll('.person-handle').forEach(button=>{
    button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation()});
    button.addEventListener('pointerdown',event=>{if(activeTransfers.has(event.pointerId))return;activeTransfers.set(event.pointerId,{origin:button.dataset.origin,role:button.dataset.role,startX:event.clientX,startY:event.clientY,dragging:false,ghost:null,hover:null});button.setPointerCapture(event.pointerId);event.preventDefault()});
    button.addEventListener('pointermove',event=>{const state=activeTransfers.get(event.pointerId);if(!state)return;const distance=Math.hypot(event.clientX-state.startX,event.clientY-state.startY);if(distance>12&&!state.dragging){state.dragging=true;state.ghost=document.createElement('div');state.ghost.className='inline-drag-ghost';state.ghost.innerHTML=personIcon;document.body.appendChild(state.ghost)}if(state.dragging){state.ghost.style.left=`${event.clientX}px`;state.ghost.style.top=`${event.clientY}px`;const area=document.elementFromPoint(event.clientX,event.clientY)?.closest('.dotacion')?.dataset.area||null;state.hover=area&&areaSupportsRole(area,state.role)?area:null;clearDropState()}});
    button.addEventListener('pointerup',event=>{const state=activeTransfers.get(event.pointerId);if(!state)return;const area=state.dragging?document.elementFromPoint(event.clientX,event.clientY)?.closest('.dotacion')?.dataset.area:null,destination=area&&areaSupportsRole(area,state.role)?area:null;state.ghost?.remove();activeTransfers.delete(event.pointerId);clearDropState();if(state.dragging)moveOne(state.origin,destination,state.role);event.preventDefault();event.stopPropagation()});
    button.addEventListener('pointercancel',event=>{const state=activeTransfers.get(event.pointerId);if(!state)return;state.ghost?.remove();activeTransfers.delete(event.pointerId);clearDropState();event.preventDefault()});
  });
}
function showTransferToast(){
  let toast=document.querySelector('#transferToast');if(!toast){toast=document.createElement('div');toast.id='transferToast';toast.className='transfer-toast';toast.innerHTML='<span></span><button class="toast-close" aria-label="Cerrar">×</button>';document.body.appendChild(toast);toast.querySelector('.toast-close').addEventListener('click',()=>toast.classList.remove('show'))}
  toast.querySelector('span').innerHTML=`Se movió <b>1 ${roleNames[lastMove.role]}</b> de ${areaNames[lastMove.origin]} a ${areaNames[lastMove.destination]}`;requestAnimationFrame(()=>toast.classList.add('show'));clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),5000);
}
const tip=document.createElement('div');tip.id='transferTip';tip.className='transfer-tip';tip.textContent='Ahora toca el área de destino';document.body.appendChild(tip);

const allValues=()=>[...document.querySelectorAll('.stat b,.editable-cell')].filter(element=>!element.closest('.dotacion'));
const todayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago'}).format(new Date());
const dayNumber=date=>Date.parse(`${date}T00:00:00Z`)/86400000;
function writeSafetyCounter(value){const safeValue=Math.max(0,Math.trunc(Number(value)||0));document.querySelector('.days-safe b').textContent=safeValue;localStorage.setItem(HSE_STORAGE_KEY,JSON.stringify({value:safeValue,date:todayKey()}))}
function syncSafetyCounter(simulated=false){let state;try{state=JSON.parse(localStorage.getItem(HSE_STORAGE_KEY)||'null')}catch{state=null}const today=todayKey(),initial=Math.max(0,Number.parseInt(document.querySelector('.days-safe b').textContent,10)||0);if(!state?.date){state={value:initial,date:today}}else{const elapsed=Math.max(0,Math.floor(dayNumber(today)-dayNumber(state.date)));state={value:Math.max(0,Number(state.value)||0)+elapsed+(simulated?1:0),date:today}}document.querySelector('.days-safe b').textContent=state.value;localStorage.setItem(HSE_STORAGE_KEY,JSON.stringify(state))}
function updatePreventionGauge(){const gauge=document.querySelector('.prevention-index'),valueTarget=gauge?.querySelector('b');if(!gauge||!valueTarget)return;const value=Math.max(0,Math.min(100,Number.parseFloat(valueTarget.textContent)||0)),angle=(-180+value*1.8)*Math.PI/180,x=100+Math.cos(angle)*80,y=100+Math.sin(angle)*80,marker=gauge.querySelector('.prevention-hub');valueTarget.textContent=`${Math.round(value)}%`;gauge.querySelector('.prevention-needle').style.display='none';marker.setAttribute('cx',x.toFixed(2));marker.setAttribute('cy',y.toFixed(2));gauge.classList.toggle('low',value<=80);gauge.classList.toggle('medium',value>80&&value<90);gauge.classList.toggle('high',value>=90);gauge.setAttribute('aria-label',`Índice de prevención ${Math.round(value)} por ciento. Tocar para modificar`)}
function writePreventionState(value,entered=true){const safeValue=Math.max(0,Math.min(100,Number.parseFloat(value)||0)),target=document.querySelector('.prevention-index b');if(!target)return;target.textContent=`${safeValue}%`;target.dataset.entered=String(entered);localStorage.setItem(PREVENTION_STORAGE_KEY,JSON.stringify({date:todayKey(),value:safeValue,entered,updatedAt:new Date().toISOString()}));updatePreventionGauge()}
function syncPreventionState(){let state;try{state=JSON.parse(localStorage.getItem(PREVENTION_STORAGE_KEY)||'null')}catch{state=null}writePreventionState(state?.value??0,Boolean(state?.entered))}
function initializeHsePrevention(){const card=[...document.querySelectorAll('.side-card')].find(item=>item.querySelector('h2')?.textContent.includes('HSE')),header=card?.querySelector('header'),content=card?.querySelector(':scope>div');if(!card||!header||!content)return;card.classList.add('hse-card');const daysView=document.createElement('div'),gauge=document.createElement('div'),toggle=document.createElement('button');daysView.className='hse-days-view';[...content.children].forEach(child=>daysView.append(child));gauge.className='hse-prevention-view';gauge.innerHTML='<span>ÍNDICE DE PREVENCIÓN</span><button type="button" class="prevention-index" data-label="Índice de prevención"><svg viewBox="0 0 200 125" aria-hidden="true"><path class="prevention-track" d="M20 100 A80 80 0 0 1 180 100"/><path class="prevention-range range-red" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><path class="prevention-range range-yellow" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><path class="prevention-range range-green" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><line class="prevention-needle" x1="100" y1="100" x2="100" y2="32"/><circle class="prevention-hub" cx="100" cy="100" r="7"/><text x="13" y="117">0</text><text x="145" y="44">80</text><text x="165" y="65">90</text><text x="177" y="117">100</text></svg><b data-entered="false">0%</b></button><div class="prevention-legend"><span><i></i>≤ 80%</span><span><i></i>80–90%</span><span><i></i>≥ 90%</span></div>';toggle.type='button';toggle.className='hse-view-toggle';toggle.innerHTML='<i data-lucide="calendar-days"></i>';toggle.setAttribute('aria-label','Ver días sin accidentes');toggle.title='Ver días sin accidentes';header.append(toggle);content.replaceChildren(daysView,gauge);const setView=view=>{const showIndex=view==='indice';card.classList.toggle('show-prevention',showIndex);toggle.innerHTML=`<i data-lucide="${showIndex?'calendar-days':'gauge'}"></i>`;toggle.setAttribute('aria-label',showIndex?'Ver días sin accidentes':'Ver índice de prevención');toggle.title=showIndex?'Ver días sin accidentes':'Ver índice de prevención';localStorage.setItem('dhl-hse-vista',view);window.lucide?.createIcons()};toggle.addEventListener('click',()=>setView(card.classList.contains('show-prevention')?'dias':'indice'));gauge.querySelector('.prevention-index').addEventListener('click',openEditor);syncPreventionState();setView(localStorage.getItem('dhl-hse-vista')||'indice')}
function qraTargets(){return[...document.querySelectorAll('.radar-score b')]}
function writeQraState(){const targets=qraTargets();localStorage.setItem(QRA_STORAGE_KEY,JSON.stringify({date:todayKey(),values:targets.map(target=>Math.max(0,Math.min(100,Number.parseFloat(target.textContent)||0))),entered:targets.map(target=>target.dataset.entered==='true'),updatedAt:new Date().toISOString()}));updateQraRadar()}
function syncQraState(){let state;try{state=JSON.parse(localStorage.getItem(QRA_STORAGE_KEY)||'null')}catch{state=null}const targets=qraTargets();if(state?.values?.length===targets.length)targets.forEach((target,index)=>{target.textContent=`${Math.max(0,Math.min(100,Number.parseFloat(state.values[index])||0))}%`;target.dataset.entered=String(Boolean(state.entered?.[index]))});else{targets.forEach(target=>{target.textContent='0%';target.dataset.entered='false'});writeQraState()}}
function writeCustomerAuditState(value,entered=true){const target=document.querySelector('.customer-audit-score b');if(!target)return;const safeValue=Math.max(0,Math.min(100,Number.parseFloat(value)||0));target.textContent=`${Math.round(safeValue)}%`;target.dataset.entered=String(entered);target.closest('.customer-audit-view')?.classList.toggle('on-target',entered&&safeValue>=90);target.closest('.customer-audit-view')?.style.setProperty('--audit-level',`${safeValue}%`);localStorage.setItem(CUSTOMER_AUDIT_STORAGE_KEY,JSON.stringify({date:todayKey(),value:safeValue,entered,updatedAt:new Date().toISOString()}))}
function syncCustomerAuditState(){let state;try{state=JSON.parse(localStorage.getItem(CUSTOMER_AUDIT_STORAGE_KEY)||'null')}catch{state=null}writeCustomerAuditState(state?.value??0,Boolean(state?.entered))}
function updateQraRadar(){
  const radar=document.querySelector('.qra-radar');if(!radar)return;const values=qraTargets().map(target=>Math.max(0,Math.min(100,Number.parseFloat(target.textContent)||0))),average=Math.round(values.reduce((total,value)=>total+value,0)/values.length),point=(index,radius)=>{const angle=(-90+index*72)*Math.PI/180;return`${50+Math.cos(angle)*radius},${50+Math.sin(angle)*radius}`},polygon=values.map((value,index)=>point(index,38*value/100)).join(' ');
  radar.querySelector('.qra-radar-value').textContent=`${average}%`;radar.querySelector('.qra-data-shape').setAttribute('points',polygon);radar.setAttribute('aria-label',`Promedio QRA 5S ${average} por ciento. Tocar para ver detalle`);
}
function initializeQraRadar(){
  const card=document.querySelector('.qra-card'),content=card?.querySelector(':scope>div'),grid=card?.querySelector('.qra-grid'),header=card?.querySelector('header');if(!card||!content||!grid||!header)return;
  const point=(index,radius)=>{const angle=(-90+index*72)*Math.PI/180;return`${50+Math.cos(angle)*radius},${50+Math.sin(angle)*radius}`},points=Array.from({length:5},(_,index)=>point(index,38)).join(' '),midPoints=Array.from({length:5},(_,index)=>point(index,19)).join(' ');
  const radar=document.createElement('button');radar.type='button';radar.className='qra-radar';radar.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><polygon class="qra-grid-outer" points="${points}"/><polygon class="qra-grid-inner" points="${midPoints}"/><line x1="50" y1="50" x2="50" y2="12"/><line x1="50" y1="50" x2="86.1" y2="38.3"/><line x1="50" y1="50" x2="72.3" y2="80.7"/><line x1="50" y1="50" x2="27.7" y2="80.7"/><line x1="50" y1="50" x2="13.9" y2="38.3"/><polygon class="qra-data-shape" points="50,50 50,50 50,50 50,50 50,50"/><text x="50" y="7">1S</text><text x="93" y="38">2S</text><text x="77" y="91">3S</text><text x="23" y="91">4S</text><text x="7" y="38">5S</text></svg><span><b class="qra-radar-value">0%</b></span>`;
  const audit=document.createElement('div');audit.className='customer-audit-view';audit.innerHTML='<span>AUDITORÍA DE CLIENTE</span><button type="button" class="customer-audit-score" data-label="Auditoría de cliente"><b data-entered="false">0%</b><small>Tocar para ingresar resultado</small></button><div class="customer-audit-scale"><i></i><span>0%</span><strong>Meta 90%</strong><span>100%</span></div>';
  const controls=document.createElement('div');controls.className='qra-view-controls';controls.innerHTML=`<button type="button" class="qra-view-toggle" aria-label="Ver detalle 5S" title="Detalle 5S">${controlIcon('list')}</button><button type="button" class="customer-audit-toggle" aria-label="Ver auditoría de cliente" title="Auditoría de cliente"><i data-lucide="clipboard-check"></i></button>`;
  header.append(controls);content.prepend(radar);content.append(audit);
  const detailButton=controls.querySelector('.qra-view-toggle'),auditButton=controls.querySelector('.customer-audit-toggle');
  const setView=view=>{card.dataset.qraView=view;card.classList.toggle('qra-detail-mode',view==='detalle');detailButton.setAttribute('aria-pressed',String(view==='detalle'));auditButton.setAttribute('aria-pressed',String(view==='cliente'));detailButton.innerHTML=controlIcon(view==='detalle'?'radar':'list');detailButton.setAttribute('aria-label',view==='detalle'?'Ver radar QRA':'Ver detalle 5S');auditButton.setAttribute('aria-label',view==='cliente'?'Ver radar QRA':'Ver auditoría de cliente')};
  radar.addEventListener('click',()=>setView('detalle'));detailButton.addEventListener('click',()=>setView(card.dataset.qraView==='detalle'?'radar':'detalle'));auditButton.addEventListener('click',()=>setView(card.dataset.qraView==='cliente'?'radar':'cliente'));audit.querySelector('.customer-audit-score').addEventListener('click',openEditor);syncCustomerAuditState();setView('radar');updateQraRadar();window.lucide?.createIcons();
}
function initializeBusinessLineSelector(){
  const configs=[{id:'preparacion',body:document.querySelector('#prepRows')},{id:'despacho',body:document.querySelector('#dispatchRows')}];if(configs.some(config=>!config.body))return;
  let stored=null;try{stored=JSON.parse(localStorage.getItem(BUSINESS_LINES_STORAGE_KEY)||'null')}catch{}const selections={};shifts.forEach(shift=>{selections[shift.id]={};configs.forEach(config=>{const legacy=Array.isArray(stored)?stored:Array.isArray(stored?.[config.id])?stored[config.id]:null,saved=Array.isArray(stored?.[shift.id]?.[config.id])?stored[shift.id][config.id]:legacy||businessLines;selections[shift.id][config.id]=new Set(saved.filter(line=>businessLines.includes(line)));if(!selections[shift.id][config.id].size)selections[shift.id][config.id]=new Set(businessLines)})});
  const activeShift=()=>shiftForCut(document.querySelector('#cutTime').textContent)?.id||'noche';
  const persist=()=>{const payload={};shifts.forEach(shift=>{payload[shift.id]={};configs.forEach(config=>payload[shift.id][config.id]=[...selections[shift.id][config.id]])});localStorage.setItem(BUSINESS_LINES_STORAGE_KEY,JSON.stringify(payload))};
  configs.forEach(config=>{config.card=config.body.closest('.focus-card');const header=config.card.querySelector('h2'),label=config.id==='preparacion'?'Preparación':'Despacho',toggle=document.createElement('button'),menu=document.createElement('div');config.toggle=toggle;config.menu=menu;toggle.type='button';toggle.className='business-lines-toggle';toggle.innerHTML=controlIcon('filter');toggle.title=`Filtrar líneas de ${label}`;toggle.setAttribute('aria-label',`Filtrar líneas de ${label}`);toggle.setAttribute('aria-expanded','false');menu.className=`business-lines-menu${config.id==='despacho'?' business-lines-menu-up':''}`;menu.hidden=true;menu.innerHTML=`<strong>Líneas de ${label}</strong>${businessLines.map(line=>`<button type="button" data-business-option="${line}"><span>✓</span>${line}</button>`).join('')}`;header.append(toggle);config.card.append(menu);
     config.paint=()=>{const selected=selections[activeShift()][config.id];config.body.querySelectorAll('tr').forEach(row=>row.hidden=!selected.has(row.dataset.businessLine));config.card.dataset.visibleLines=selected.size;menu.querySelectorAll('[data-business-option]').forEach(option=>{const active=selected.has(option.dataset.businessOption);option.classList.toggle('active',active);option.setAttribute('aria-pressed',String(active));option.querySelector('span').textContent=active?'✓':''})};toggle.addEventListener('click',()=>{const opening=menu.hidden;menu.hidden=!opening;config.card.classList.toggle('business-menu-open',opening);toggle.setAttribute('aria-expanded',String(opening))});menu.addEventListener('click',event=>{const option=event.target.closest('[data-business-option]');if(!option)return;const selected=selections[activeShift()][config.id],line=option.dataset.businessOption;if(selected.has(line)){if(selected.size===1)return;selected.delete(line)}else selected.add(line);config.paint();persist()})});
  refreshBusinessLineFilters=()=>configs.forEach(config=>config.paint());refreshBusinessLineFilters();persist();
  window.lucide?.createIcons();
}
function migrateSnapshotShape(saved){if(!saved?.values)return saved;const targets=allValues(),newCells=[...document.querySelectorAll('#prepRows tr[data-business-line="WLM RM"] .editable-cell')],insertAt=targets.indexOf(newCells[0]);if(newCells.length&&insertAt>=0&&saved.values.length===targets.length-newCells.length){saved.values=[...saved.values];saved.entered=[...(saved.entered||saved.values.map(()=>false))];saved.values.splice(insertAt,0,...newCells.map(()=>'0'));saved.entered.splice(insertAt,0,...newCells.map(()=>false))}return saved}
function getSnapshot(){normalizeDispatchCrew();return{schemaVersion:4,values:allValues().map(element=>element.textContent),entered:allValues().map(element=>element.dataset.entered==='true'),notes:document.querySelector('textarea[data-meeting-notes]')?.value||'',cut:document.querySelector('#cutTime').textContent,crew:structuredClone(crew),crewEntered:structuredClone(crewEntered),transferBalance:structuredClone(transferBalance),expectedKilos:structuredClone(expectedKilos),...(activeInheritedFrom?{inheritedFrom:activeInheritedFrom}:{})}}
function emptyDailyRecord(){return{date:todayKey(),sessions:{},drafts:{},expectedKilos:emptyExpectedKilos(),updatedAt:null}}
function readDailyRecord(){try{const parsed=JSON.parse(localStorage.getItem(JSON_STORAGE_KEY)||'null');if(parsed?.date===todayKey()){const record={...parsed,sessions:parsed.sessions||{},drafts:parsed.drafts||{}};Object.values(record.sessions).forEach(migrateSnapshotShape);Object.values(record.drafts).forEach(migrateSnapshotShape);const latest=[...Object.values(record.sessions),...Object.values(record.drafts)].sort((a,b)=>new Date(b.updatedAt||0)-new Date(a.updatedAt||0))[0];record.expectedKilos={in:sanitizeExpectedKilos(record.expectedKilos?.in??latest?.expectedKilos?.in),out:sanitizeExpectedKilos(record.expectedKilos?.out??latest?.expectedKilos?.out)};return record}localStorage.removeItem(JSON_STORAGE_KEY);return emptyDailyRecord()}catch{localStorage.removeItem(JSON_STORAGE_KEY);return emptyDailyRecord()}}
function writeDailyRecord(){localStorage.setItem(JSON_STORAGE_KEY,JSON.stringify(dailyRecord))}
function persistCurrentDraft(){if(!dirty||!dailyRecord)return;const snapshot={...getSnapshot(),completed:false,updatedAt:new Date().toISOString()};dailyRecord.drafts[snapshot.cut]=snapshot;dailyRecord.updatedAt=snapshot.updatedAt;writeDailyRecord()}
function markDirty(){activeInheritedFrom=null;dirty=true;document.body.classList.add('has-unsaved');const current=document.querySelector(`.cut-chip[data-cut="${document.querySelector('#cutTime').textContent}"]`);current?.classList.remove('complete');current?.classList.add('incomplete');persistCurrentDraft();document.querySelector('#lastSaved').textContent='Cambios guardados localmente · reunión sin confirmar'}
function validateCurrentMeeting(){
  const missing=[],sectionNames={foco:'Foco',productividad:'Productividad',horas:'Horas'};
  for(const [indicator,label] of Object.entries(sectionNames)){
    document.querySelectorAll(`.data-card[data-indicator="${indicator}"]`).forEach(card=>{
      const targets=[...card.querySelectorAll('.stat b,.editable-cell')].filter(target=>!target.closest('tr')?.hidden);
      if(!targets.some(target=>target.dataset.entered==='true'))missing.push(`${label} · ${areaNames[card.dataset.area]||card.dataset.area}`);
    });
  }
  Object.entries(crewEntered).forEach(([area,roles])=>{if(!roles.operativo&&!roles.grua)missing.push(`Dotación · ${areaNames[area]}`)});
  return{valid:missing.length===0,missing};
}
function paintMeetingStates(){document.querySelectorAll('.cut-chip').forEach(button=>{const session=dailyRecord?.sessions?.[button.dataset.cut],hasDraft=Boolean(dailyRecord?.drafts?.[button.dataset.cut]),complete=Boolean(session?.validation?.valid&&!hasDraft),warning=Boolean(session&&!session?.validation?.valid&&!hasDraft);button.classList.toggle('complete',complete);button.classList.toggle('warning',warning);button.classList.toggle('incomplete',!complete&&!warning)});document.querySelectorAll('.shift-group').forEach(group=>{const buttons=[...group.querySelectorAll('.cut-chip')],allComplete=buttons.every(button=>button.classList.contains('complete')),hasWarning=buttons.some(button=>button.classList.contains('warning'));group.classList.toggle('complete-shift',allComplete);group.classList.toggle('warning-shift',!allComplete&&hasWarning)})}
function seedNextMeeting(snapshot){const shift=shiftForCut(snapshot.cut),index=shift?.cuts.indexOf(snapshot.cut)??-1;if(!shift||index<0||index>=shift.cuts.length-1)return;const nextCut=shift.cuts[index+1];if(dailyRecord.sessions[nextCut]||snapshotHasEnteredData(dailyRecord.drafts[nextCut])&&!dailyRecord.drafts[nextCut].inheritedFrom)return;const inherited=structuredClone(snapshot);inherited.cut=nextCut;inherited.completed=false;inherited.inheritedFrom=snapshot.cut;inherited.updatedAt=new Date().toISOString();delete inherited.validation;dailyRecord.drafts[nextCut]=inherited}
function saveCurrentMeeting(){const validation=validateCurrentMeeting(),snapshot={...getSnapshot(),completed:validation.valid,validation,updatedAt:new Date().toISOString()};delete snapshot.inheritedFrom;dailyRecord.sessions[snapshot.cut]=snapshot;delete dailyRecord.drafts[snapshot.cut];seedNextMeeting(snapshot);dailyRecord.updatedAt=snapshot.updatedAt;writeDailyRecord();activeInheritedFrom=null;dirty=false;document.body.classList.remove('has-unsaved');paintMeetingStates();paintOmsCube();if(document.body.classList.contains('summary-open'))renderSummary();document.querySelector('#lastSaved').textContent=validation.valid?`Reunión ${snapshot.cut} completa · guardada`:`Reunión ${snapshot.cut} guardada incompleta · faltan ${validation.missing.length} secciones`}
function applySnapshot(saved){if(!saved)return;if(saved.values?.length){const targets=allValues(),limit=Math.min(saved.values.length,targets.length);saved.values.slice(0,limit).forEach((value,index)=>{const target=targets[index];target.textContent=target.classList.contains('prep-advance')?String(value).replace('%',''):value;const wasEntered=saved.entered?.[index]??Number.parseFloat(String(value).replace(',','.'))!==0;target.dataset.entered=String(Boolean(wasEntered))})}const notes=document.querySelector('textarea[data-meeting-notes]');if(saved.notes!==undefined&&notes)notes.value=saved.notes;if(saved.cut){document.querySelector('#cutTime').textContent=saved.cut;document.querySelectorAll('.cut-chip').forEach(button=>button.classList.toggle('active',button.dataset.cut===saved.cut))}if(saved.crew?.recepcion){for(const area of Object.keys(crew))crew[area]={...crew[area],...saved.crew[area]}}if(saved.crewEntered)crewEntered=structuredClone(saved.crewEntered);else for(const area of Object.keys(crewEntered)){crewEntered[area].operativo=crew[area].operativo!==0;crewEntered[area].grua=crew[area].grua!==0}normalizeDispatchCrew()}
function blankSnapshot(cut){const blank=structuredClone(initialSnapshot);blank.cut=cut;blank.notes='';blank.values=blank.values.map(()=>'0');blank.entered=blank.values.map(()=>false);blank.transferBalance=emptyTransferBalance();Object.keys(blank.crew).forEach(area=>{blank.crew[area].operativo=0;blank.crew[area].grua=0;blank.crew[area].planOperativo=0;blank.crew[area].planGrua=0;blank.crewEntered[area].operativo=false;blank.crewEntered[area].grua=false});return blank}
function shiftForCut(cut){return shifts.find(shift=>shift.cuts.includes(cut))}
function snapshotHasEnteredData(snapshot){return Boolean(snapshot&&(snapshot.entered?.some(Boolean)||Object.values(snapshot.crewEntered||{}).some(roles=>roles?.operativo||roles?.grua)||Object.values(snapshot.expectedKilos||{}).some(Boolean)))}
function inheritedSnapshot(cut){
  const shift=shiftForCut(cut),index=shift?.cuts.indexOf(cut)??-1;
  if(index<1)return null;
  for(let position=index-1;position>=0;position--){
    const previousCut=shift.cuts[position],snapshot=dailyRecord.sessions[previousCut];
    if(snapshot&&snapshotHasEnteredData(snapshot)){
      const inherited=structuredClone(snapshot);
      inherited.cut=cut;inherited.completed=false;inherited.inheritedFrom=previousCut;delete inherited.validation;delete inherited.updatedAt;
      return{snapshot:inherited,source:previousCut};
    }
  }
  return null;
}
function storeCurrentDraft(){if(!dirty)return;persistCurrentDraft();paintMeetingStates()}
function legacyLoadMeeting(cut){const saved=dailyRecord.sessions[cut],draft=dailyRecord.drafts[cut],inherited=!saved&&!draft?inheritedSnapshot(cut):null,source=draft||saved||inherited?.snapshot||blankSnapshot(cut);applySnapshot({...structuredClone(source),cut});document.querySelector('#cutTime').textContent=cut;updateInlineCounts();dirty=Boolean(draft);document.body.classList.toggle('has-unsaved',dirty);document.querySelector('#lastSaved').textContent=draft?`Borrador ${cut} · sin guardar`:saved?`Reunión ${cut} completada`:inherited?`Base heredada desde ${inherited.source}`:'Inicio de turno · reunión pendiente'}
function resetForNewDay(simulated=false){syncSafetyCounter(simulated);activeDate=todayKey();dailyRecord=emptyDailyRecord();expectedKilos=emptyExpectedKilos();paintExpectedKilos();writeDailyRecord();syncQraState();syncCustomerAuditState();syncPreventionState();paintMeetingStates();paintOmsCube();loadMeeting(cuts[0]);if(document.body.classList.contains('summary-open'))renderSummary();closeCalculators();closeClearPanel();document.querySelector('#lastSaved').textContent=simulated?'Cambio de día simulado · tablero limpio':'Nuevo día · tablero limpio'}
function loadMeeting(cut){const saved=dailyRecord.sessions[cut],storedDraft=dailyRecord.drafts[cut],draft=snapshotHasEnteredData(storedDraft)?storedDraft:null;if(storedDraft&&!draft){delete dailyRecord.drafts[cut];writeDailyRecord()}const inherited=!saved&&!draft?inheritedSnapshot(cut):null,source=draft||saved||inherited?.snapshot||blankSnapshot(cut);activeInheritedFrom=source.inheritedFrom||inherited?.source||null;applySnapshot({...structuredClone(source),cut});transferBalance=structuredClone(source.transferBalance||emptyTransferBalance());normalizeDispatchCrew();document.querySelector('#cutTime').textContent=cut;updateInlineCounts();dirty=Boolean(draft||inherited);document.body.classList.toggle('has-unsaved',dirty);document.querySelector('#lastSaved').textContent=draft?`Borrador ${cut} · sin guardar`:saved?`Reunión ${cut} completada`:inherited?`Base heredada desde ${inherited.source} · sin guardar`:'Inicio de turno · reunión pendiente'}
function checkDayChange(){if(todayKey()!==activeDate)resetForNewDay()}
const systemDateFormatter=new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'2-digit',year:'2-digit'});
const systemTimeFormatter=new Intl.DateTimeFormat('es-CL',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
function isoWeekNumber(date=new Date()){const day=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate())),weekday=day.getUTCDay()||7;day.setUTCDate(day.getUTCDate()+4-weekday);const yearStart=new Date(Date.UTC(day.getUTCFullYear(),0,1));return Math.ceil((((day-yearStart)/86400000)+1)/7)}
function paintWeekNumber(date=new Date()){const week=isoWeekNumber(date),value=document.querySelector('#weekNumberValue'),indicator=document.querySelector('#weekNumber');if(!value||!indicator)return;value.textContent=String(week);indicator.setAttribute('aria-label',`Semana calendario ${week}, calculada automáticamente con la fecha del dispositivo`)}
function paintSystemDate(){const now=new Date();document.querySelector('#systemDate').textContent=systemDateFormatter.format(now).replace(/[.-]/g,'/');document.querySelector('#systemTime').textContent=systemTimeFormatter.format(now);paintWeekNumber(now)}
function paintExpectedKilos(){document.querySelectorAll('[data-kilos-field]').forEach(input=>input.value=formatExpectedKilos(expectedKilos[input.dataset.kilosField]))}
function setExpectedKilosValue(field,value,persist=true){const digits=sanitizeExpectedKilos(value);expectedKilos[field]=digits;const input=document.querySelector(`[data-kilos-field="${field}"]`);if(input)input.value=formatExpectedKilos(digits);if(dailyRecord)dailyRecord.expectedKilos=structuredClone(expectedKilos);if(persist)markDirty();return digits}
function openExpectedKilosEditor(event){
  event.preventDefault();const input=event.currentTarget;if(input.dataset.editorId){const openCard=document.querySelector(`#${input.dataset.editorId}`);delete input.dataset.editorId;openCard?.remove();return}
  const field=input.dataset.kilosField,id=`kilos-calculator-${crypto.randomUUID?.()||Date.now()}-${Math.floor(Math.random()*999)}`,keys=['7','8','9','4','5','6','1','2','3','0','000','⌫'];let value=sanitizeExpectedKilos(expectedKilos[field])||'0',fresh=true;const card=document.createElement('section');card.className='contextual-calculator kilos-calculator';card.id=id;card.setAttribute('role','dialog');card.setAttribute('aria-label',`Kilos esperados ${field.toUpperCase()}`);card.innerHTML=`<header><span><i data-lucide="weight"></i><b>Kilos esperados ${field.toUpperCase()}</b></span><button class="calculator-close" aria-label="Cerrar">×</button></header><div class="calculator-display">${formatExpectedKilos(value)}</div><div class="calculator-keys kilos-keys">${keys.map(key=>`<button data-key="${key}"${key==='⌫'?' class="calculator-delete" aria-label="Borrar último dígito"':''}>${key==='⌫'?'<i data-lucide="delete"></i>':key}</button>`).join('')}</div><button class="calculator-save"><i data-lucide="check-circle"></i><span>Aplicar kilos</span></button>`;
  document.body.appendChild(card);input.dataset.editorId=id;const display=card.querySelector('.calculator-display'),paint=()=>display.textContent=formatExpectedKilos(value)||'0',close=()=>{delete input.dataset.editorId;card.remove()};
  card.querySelector('.calculator-close').addEventListener('click',close);card.querySelectorAll('.calculator-keys button').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.key;if(key==='⌫'){fresh=false;value=value.length>1?value.slice(0,-1):'0'}else{if(fresh||value==='0')value='';fresh=false;value=sanitizeExpectedKilos(`${value}${key}`)||'0'}paint()}));
  card.querySelector('.calculator-save').addEventListener('click',()=>{setExpectedKilosValue(field,value);close()});makeDraggable(card,card.querySelector('header'));const rect=input.getBoundingClientRect(),left=field==='in'?rect.right-card.offsetWidth:rect.left;card.style.left=`${Math.max(10,Math.min(window.innerWidth-card.offsetWidth-10,left))}px`;card.style.top=`${Math.max(10,rect.top-card.offsetHeight-8)}px`;window.lucide?.createIcons({attrs:{'stroke-width':2}});
}
function initializeExpectedKilos(){paintExpectedKilos();document.querySelectorAll('[data-kilos-field]').forEach(input=>{input.addEventListener('input',()=>setExpectedKilosValue(input.dataset.kilosField,input.value));input.addEventListener('click',openExpectedKilosEditor);input.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openExpectedKilosEditor({currentTarget:input,preventDefault(){}})}})})}
function editableTarget(element){return element.matches('.stat,.radar-score,.days-safe,.workforce-numbers,.prevention-index,.customer-audit-score')?element.querySelector('b,strong'):element}
function editorLabel(element){return element.dataset.label||element.closest('tr')?.firstElementChild.textContent||'Valor'}
function positionCalculator(card,target,index){const rect=target.getBoundingClientRect(),width=card.offsetWidth,height=card.offsetHeight;let left=rect.right+10,top=rect.top;if(left+width>window.innerWidth-10)left=rect.left-width-10;if(left<10)left=10;if(top+height>window.innerHeight-10)top=window.innerHeight-height-10;top=Math.max(10,top+(index%3)*14);card.style.left=`${left}px`;card.style.top=`${top}px`}
function makeDraggable(card,handle){let drag=null;handle.addEventListener('pointerdown',event=>{if(drag||event.target.closest('button'))return;const rect=card.getBoundingClientRect();drag={pointerId:event.pointerId,dx:event.clientX-rect.left,dy:event.clientY-rect.top};handle.setPointerCapture(event.pointerId)});handle.addEventListener('pointermove',event=>{if(drag?.pointerId!==event.pointerId)return;card.style.left=`${Math.max(0,Math.min(window.innerWidth-card.offsetWidth,event.clientX-drag.dx))}px`;card.style.top=`${Math.max(0,Math.min(window.innerHeight-card.offsetHeight,event.clientY-drag.dy))}px`});const stop=event=>{if(drag?.pointerId===event.pointerId)drag=null};handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop)}
function openEditor(event){
  const source=event.currentTarget,target=editableTarget(source);if(target.dataset.editorId){const openCard=document.querySelector(`#${target.dataset.editorId}`);delete target.dataset.editorId;openCard?.remove();return}
  const indicator=source.closest('.data-card')?.dataset.indicator,qraScore=source.matches('.radar-score'),preventionScore=source.matches('.prevention-index'),auditScore=source.matches('.customer-audit-score'),allowNegative=indicator==='productividad',id=`calculator-${crypto.randomUUID?.()||Date.now()}-${Math.floor(Math.random()*999)}`,suffix=indicator==='horas'||qraScore||preventionScore||auditScore||target.textContent.includes('%')?'%':'';let value=target.textContent.replace(/[^0-9.,-]/g,'').replace(',','.')||'0';if(!allowNegative&&Number(value)<0)value=String(Math.abs(Number(value)));
  const keys=['7','8','9','4','5','6','1','2','3',...(allowNegative?['±']:[]),'0',',','⌫'];const card=document.createElement('section');card.className='contextual-calculator';card.id=id;card.innerHTML=`<header><span><i data-lucide="calculator"></i><b>${editorLabel(source)}</b></span><button class="calculator-close" aria-label="Cerrar">×</button></header><div class="calculator-display">${value}${suffix}</div><div class="calculator-keys${allowNegative?'':' no-negative'}">${keys.map(key=>`<button data-key="${key}"${key==='⌫'?' class="calculator-delete"':''}>${key==='⌫'?'<i data-lucide="delete"></i><span>Borrar</span>':key}</button>`).join('')}</div><button class="calculator-save"><i data-lucide="check-circle"></i><span>Aplicar valor</span></button>`;
  document.body.appendChild(card);target.dataset.editorId=id;const display=card.querySelector('.calculator-display'),paint=()=>display.textContent=`${value}${suffix}`,close=()=>{delete target.dataset.editorId;card.remove()};
  card.querySelector('.calculator-close').addEventListener('click',close);card.querySelectorAll('.calculator-keys button').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.key;if(key==='⌫')value=value.length>1?value.slice(0,-1):'0';else if(key==='±')value=value.startsWith('-')?value.slice(1):`-${value}`;else if(key===','){if(!value.includes('.'))value+='.'}else value=value==='0'?key:`${value}${key}`;paint()}));
  card.querySelector('.calculator-save').addEventListener('click',()=>{if(!allowNegative&&Number(value)<0)value='0';if((indicator==='horas'||qraScore||preventionScore||auditScore)&&Number(value)>100)value='100';target.textContent=`${value}${suffix}`;target.dataset.entered='true';if(target.closest('.days-safe')){writeSafetyCounter(value);close();return}if(target.closest('.radar-score')){writeQraState();close();return}if(target.closest('.prevention-index')){writePreventionState(value,true);close();return}if(target.closest('.customer-audit-score')){writeCustomerAuditState(value,true);close();return}const workforceField=target.closest('.workforce-numbers'),roleRow=target.closest('.workforce-role'),areaCard=target.closest('.dotacion');if(workforceField&&roleRow&&areaCard){const field=workforceField.dataset.field;crew[areaCard.dataset.area][field]=Math.max(0,Number(value)||0);if(field===roleRow.dataset.role)crewEntered[areaCard.dataset.area][roleRow.dataset.role]=true;target.textContent=crew[areaCard.dataset.area][field]}markDirty();close()});makeDraggable(card,card.querySelector('header'));positionCalculator(card,target,document.querySelectorAll('.contextual-calculator').length-1);window.lucide?.createIcons({attrs:{'stroke-width':2}});
}
document.querySelectorAll('.stat:not(.dotacion .stat),.editable-cell,.radar-score,.days-safe').forEach(element=>element.addEventListener('click',openEditor));
document.querySelector('textarea[data-meeting-notes]')?.addEventListener('input',markDirty);
document.querySelector('#saveMeeting').addEventListener('click',saveCurrentMeeting);
function simulateMeetingData(){
  transferBalance=emptyTransferBalance();
  document.querySelectorAll('.data-card[data-indicator]').forEach(card=>{
    const indicator=card.dataset.indicator;if(indicator==='dotacion')return;
    card.querySelectorAll('.stat:not(.dispatch-crane-field) b,.editable-cell').forEach((target,index)=>{const value=indicator==='productividad'?Math.floor(Math.random()*31)-10:indicator==='horas'?Math.floor(Math.random()*101):target.classList.contains('prep-advance')?Math.floor(Math.random()*151)+1:Math.floor(Math.random()*801)+1;target.textContent=indicator==='horas'?`${value}%`:value;target.dataset.entered='true'});
  });
  const basePlans={recepcion:{operativo:92,grua:22},preparacion:{operativo:45,grua:12},despacho:{operativo:33,grua:0}};
  Object.keys(crew).forEach(area=>{const base=basePlans[area];crew[area].planOperativo=Math.max(1,base.operativo+Math.floor(Math.random()*7)-3);crew[area].operativo=Math.max(1,Math.floor(crew[area].planOperativo*(.72+Math.random()*.25)));crewEntered[area].operativo=true;if(areaSupportsRole(area,'grua')){crew[area].planGrua=Math.max(1,base.grua+Math.floor(Math.random()*5)-2);crew[area].grua=Math.max(1,Math.floor(crew[area].planGrua*(.72+Math.random()*.25)));crewEntered[area].grua=true}});normalizeDispatchCrew();
  expectedKilos={in:String(Math.floor(Math.random()*999900000)+100000),out:String(Math.floor(Math.random()*999900000)+100000)};paintExpectedKilos();if(dailyRecord)dailyRecord.expectedKilos=structuredClone(expectedKilos);
  updateInlineCounts();qraTargets().forEach(target=>{target.textContent=Math.floor(Math.random()*31)+70;target.dataset.entered='true'});writeQraState();closeCalculators();markDirty();document.querySelector('#lastSaved').textContent='Datos aleatorios cargados · sin guardar';
}
document.querySelector('#simulateData').addEventListener('click',simulateMeetingData);
document.querySelector('#simulateNextDay').addEventListener('click',()=>resetForNewDay(true));
document.querySelector('#resetSafeDays').addEventListener('click',()=>{writeSafetyCounter(0);closeCalculators();document.querySelector('#lastSaved').textContent='Contador HSE reiniciado en 0'});
document.querySelectorAll('.cut-chip').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.cut===document.querySelector('#cutTime').textContent)return;storeCurrentDraft();document.querySelectorAll('.cut-chip').forEach(item=>item.classList.remove('active'));button.classList.add('active');loadMeeting(button.dataset.cut)}));
function initializeAreaMetadata(){document.querySelectorAll('.process-label').forEach((label,index)=>{const area=['recepcion','preparacion','despacho'][index];let card=label.nextElementSibling;['foco','productividad','horas','dotacion'].forEach(indicator=>{if(card?.classList.contains('data-card')){card.dataset.area=area;card.dataset.indicator=indicator;card=card.nextElementSibling}})})}
function closeCalculators(){document.querySelectorAll('.contextual-calculator').forEach(card=>card.remove());document.querySelectorAll('[data-editor-id]').forEach(target=>delete target.dataset.editorId)}
function closeClearPanel(){const panel=document.querySelector('#clearAreas');panel.classList.remove('open','choose-section');panel.setAttribute('aria-hidden','true');panel.style.removeProperty('position');panel.style.removeProperty('left');panel.style.removeProperty('top');panel.style.removeProperty('right');selectedClearArea=null}
function bindDraggableClearPanel(){
  const panel=document.querySelector('#clearAreas');let drag=null;
  const bounds=()=>({maxLeft:Math.max(8,window.innerWidth-panel.offsetWidth-8),maxTop:Math.max(8,window.innerHeight-panel.offsetHeight-8)});panel.addEventListener('pointerdown',event=>{const handle=event.target.closest('.clear-step>b');if(!handle)return;const rect=panel.getBoundingClientRect(),limits=bounds(),left=Math.max(8,Math.min(limits.maxLeft,rect.left)),top=Math.max(8,Math.min(limits.maxTop,rect.top));drag={dx:event.clientX-left,dy:event.clientY-top,pointerId:event.pointerId,handle};panel.style.position='fixed';panel.style.left=`${left}px`;panel.style.top=`${top}px`;panel.style.right='auto';handle.setPointerCapture(event.pointerId);event.preventDefault()});
  panel.addEventListener('pointermove',event=>{if(drag?.pointerId!==event.pointerId)return;const limits=bounds(),left=Math.max(8,Math.min(limits.maxLeft,event.clientX-drag.dx)),top=Math.max(8,Math.min(limits.maxTop,event.clientY-drag.dy));panel.style.left=`${left}px`;panel.style.top=`${top}px`});
  const stop=event=>{if(drag?.pointerId!==event.pointerId)return;if(drag.handle.hasPointerCapture(drag.pointerId))drag.handle.releasePointerCapture(drag.pointerId);drag=null};panel.addEventListener('pointerup',stop);panel.addEventListener('pointercancel',stop);
}
function clearSection(area,indicator){
  const card=document.querySelector(`.data-card[data-area="${area}"][data-indicator="${indicator}"]`);if(!card)return;
  if(indicator==='foco')card.querySelectorAll('.stat b,.editable-cell').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  if(indicator==='productividad'||indicator==='horas')card.querySelectorAll('.stat b').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  if(indicator==='dotacion'){settleTransfers();crew[area].operativo=0;crew[area].grua=0;crew[area].planOperativo=0;crew[area].planGrua=0;crewEntered[area].operativo=false;crewEntered[area].grua=false;updateInlineCounts()}
  closeCalculators();closeClearPanel();markDirty();const sectionNames={foco:'Foco',productividad:'Productividad',horas:'Horas',dotacion:'Dotación'};document.querySelector('#lastSaved').textContent=`${areaNames[area]} · ${sectionNames[indicator]} limpiado · sin guardar`;
}
function clearEverything(){
  transferBalance=emptyTransferBalance();
  document.querySelectorAll('.data-card[data-indicator="foco"] .stat b,.data-card[data-indicator="foco"] .editable-cell').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  document.querySelectorAll('.data-card[data-indicator="productividad"] .stat b,.data-card[data-indicator="horas"] .stat b').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  Object.keys(crew).forEach(area=>{crew[area].operativo=0;crew[area].grua=0;crew[area].planOperativo=0;crew[area].planGrua=0;crewEntered[area].operativo=false;crewEntered[area].grua=false});updateInlineCounts();closeCalculators();closeClearPanel();markDirty();document.querySelector('#lastSaved').textContent='Horario actual limpiado · sin guardar';
}
function summarySnapshots(){
  return cuts.map(cut=>({cut,snapshot:dailyRecord.sessions[cut]||null}));
}
function summaryMetrics(snapshot){
  if(!snapshot)return null;const areaKeys=['recepcion','preparacion','despacho'],grouped={foco:{},productividad:{},horas:{}},targets=allValues(),valid=values=>values.filter(value=>value!==null),sum=values=>valid(values).reduce((total,value)=>total+value,0),average=values=>valid(values).length?sum(values)/valid(values).length:null,percent=(done,total)=>done!==null&&total?Math.max(0,Math.min(100,done/total*100)):null;
  areaKeys.forEach(area=>Object.keys(grouped).forEach(indicator=>grouped[indicator][area]=[]));
  (snapshot.values||[]).forEach((value,index)=>{const card=targets[index]?.closest('.data-card'),indicator=card?.dataset.indicator,area=card?.dataset.area;if(grouped[indicator]?.[area])grouped[indicator][area].push(snapshot.entered?.[index]===false?null:Number.parseFloat(String(value).replace(',','.'))||0)});
  const reception=grouped.foco.recepcion,preparation=grouped.foco.preparacion,dispatching=grouped.foco.despacho,prepAssigned=preparation.filter((_,index)=>index%3===1),prepAdvance=preparation.filter((_,index)=>index%3===2),dispatchAssigned=dispatching.filter((_,index)=>index%4===0),dispatched=dispatching.filter((_,index)=>index%4===3),foco={recepcion:percent(reception[1]===null&&reception[2]===null?null:(reception[1]||0)+(reception[2]||0),reception[0]),preparacion:percent(valid(prepAdvance).length?sum(prepAdvance):null,sum(prepAssigned)),despacho:percent(valid(dispatched).length?sum(dispatched):null,sum(dispatchAssigned))},productividad={},horas={},dotacion={};
  areaKeys.forEach(area=>{const productivityValues=area==='despacho'?grouped.productividad[area].slice(0,1):grouped.productividad[area],hourValues=area==='despacho'?grouped.horas[area].slice(0,1):grouped.horas[area];productividad[area]=average(productivityValues);const hourAverage=average(hourValues);horas[area]=hourAverage===null?null:Math.max(0,Math.min(100,hourAverage));const staff=snapshot.crew?.[area]||{},staffEntered=snapshot.crewEntered?.[area],balance=snapshot.transferBalance?.[area]||{},hasCranes=areaSupportsRole(area,'grua'),hasAttendance=staffEntered?staffEntered.operativo||(hasCranes&&staffEntered.grua):true,attended=(Number(staff.operativo)||0)-(Number(balance.operativo)||0)+(hasCranes?(Number(staff.grua)||0)-(Number(balance.grua)||0):0),planned=(Number(staff.planOperativo)||0)+(hasCranes?(Number(staff.planGrua)||0):0);dotacion[area]=hasAttendance?percent(attended,planned):null});
  return{foco,productividad,horas,dotacion};
}
function paintOmsCube(){
  const card=document.querySelector('.summary-access-card'),cube=card?.querySelector('.oms-daily-cube');if(!cube||!dailyRecord)return;
  const saved=summarySnapshots().filter(record=>record.snapshot),scores=[];
  saved.forEach(record=>{const metrics=summaryMetrics(record.snapshot);Object.keys(areaNames).forEach(area=>{const productivity=metrics.productividad[area],hours=metrics.horas[area],attendance=metrics.dotacion[area];if(productivity!==null&&hours!==null&&attendance!==null)scores.push(Math.max(0,100+productivity)/100*(hours/100)*(attendance/100)*100)})});
  const value=scores.length?scores.reduce((total,score)=>total+score,0)/scores.length:null;
  cube.style.setProperty('--oms-cube-level',`${Math.max(0,Math.min(100,value??0))}%`);cube.querySelector('b').textContent=value===null?'—':`${Math.round(value)}%`;
  card.querySelector('#openSummary').setAttribute('aria-label',`Abrir OMS. Cubo global ${value===null?'sin datos':`${Math.round(value)} por ciento`}`);
}
function summaryLineChart(chart,records){
  const areaKeys=['recepcion','preparacion','despacho'],colors={recepcion:'#43bff2',preparacion:'#ffd23f',despacho:'#ef535b'},labels={recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'},width=900,height=220,left=48,right=880,top=18,bottom=178,x=index=>left+(right-left)*index/(cuts.length-1),y=value=>top+(chart.max-value)/(chart.max-chart.min)*(bottom-top),ticks=Array.from({length:5},(_,index)=>chart.max-(chart.max-chart.min)*index/4);
  const grid=ticks.map(value=>`<line x1="${left}" y1="${y(value)}" x2="${right}" y2="${y(value)}"/><text x="${left-8}" y="${y(value)+4}" text-anchor="end">${Math.round(value)}${chart.unit}</text>`).join(''),bands=['noche','manana','tarde'].map((shift,index)=>`<rect class="shift-band ${shift}" x="${Math.max(0,x(index*3)-42)}" y="${top}" width="${index===2?right-(x(6)-42):x(index*3+3)-x(index*3)}" height="${bottom-top}"/>`).join('');
  const series=areaKeys.map(area=>{const values=records.map(record=>record.metrics?.[chart.key]?.[area]??null),segments=values.slice(0,-1).map((value,index)=>value!==null&&values[index+1]!==null?`<line class="series-line" x1="${x(index)}" y1="${y(value)}" x2="${x(index+1)}" y2="${y(values[index+1])}"/>`:'').join(''),points=values.map((value,index)=>value===null?'':`<g class="series-point"><circle cx="${x(index)}" cy="${y(value)}" r="4"><title>${labels[area]} · ${records[index].cut}: ${value.toFixed(1)}${chart.unit}</title></circle><text x="${x(index)}" y="${Math.max(12,y(value)-8)}" text-anchor="middle">${Math.round(value)}${chart.unit}</text></g>`).join('');return`<g class="area-series ${area}" style="--series:${colors[area]}">${segments}${points}</g>`}).join('');
  const hours=records.map((record,index)=>`<text class="axis-hour" x="${x(index)}" y="205" text-anchor="middle">${record.cut}</text>`).join('');
  return`<article class="summary-chart line-chart"><header><div><i data-lucide="${chart.icon}"></i><span><h3>${chart.title}</h3><small>${chart.description}</small></span></div><div class="area-legend">${areaKeys.map(area=>`<span><i style="background:${colors[area]}"></i>${labels[area]}</span>`).join('')}</div></header><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-label="${chart.title}">${bands}<g class="chart-grid">${grid}</g>${series}${hours}</svg></article>`;
}
function summaryAreaChart(area,records,metrics){
  const areaInfo={recepcion:{label:'Recepción',icon:'package-open'},preparacion:{label:'Preparación',icon:'boxes'},despacho:{label:'Despacho',icon:'truck'}}[area],shiftColors={noche:'#43bff2',manana:'#ffd23f',tarde:'#ef535b'},width=900,height=108,left=45,right=880,top=12,bottom=72,x=index=>left+(right-left)*index/(cuts.length-1);
  const metricCharts=metrics.map(metric=>{const y=value=>top+(metric.max-value)/(metric.max-metric.min)*(bottom-top),values=records.map(record=>record.metrics?.[metric.key]?.[area]??null),gridValues=metric.min<0?[metric.max,0,metric.min]:[metric.max,metric.max/2,metric.min],grid=gridValues.map(value=>`<line x1="${left}" y1="${y(value)}" x2="${right}" y2="${y(value)}"/><text x="${left-7}" y="${y(value)+3}" text-anchor="end">${Math.round(value)}${metric.unit}</text>`).join(''),segments=values.slice(0,-1).map((value,index)=>{if(value===null||values[index+1]===null)return'';const currentShift=shiftForCut(records[index].cut)?.id,nextShift=shiftForCut(records[index+1].cut)?.id;if(currentShift!==nextShift)return'';return`<line class="shift-series ${currentShift}" x1="${x(index)}" y1="${y(value)}" x2="${x(index+1)}" y2="${y(values[index+1])}"/>`}).join(''),points=values.map((value,index)=>{if(value===null)return'';const shift=shiftForCut(records[index].cut)?.id||'noche';return`<g class="shift-point ${shift}"><circle cx="${x(index)}" cy="${y(value)}" r="4"><title>${areaInfo.label} · ${metric.title} · ${records[index].cut}: ${value.toFixed(1)}${metric.unit}</title></circle><text x="${x(index)}" y="${Math.max(9,y(value)-7)}" text-anchor="middle">${Math.round(value)}${metric.unit}</text></g>`}).join(''),hours=records.map((record,index)=>`<text class="axis-hour" x="${x(index)}" y="99" text-anchor="middle">${record.cut}</text>`).join('');return`<section class="area-metric-chart"><div><i data-lucide="${metric.icon}"></i><span><b>${metric.title}</b><small>${metric.description}</small></span></div><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none"><g class="chart-grid">${grid}</g>${segments}${points}${hours}</svg></section>`}).join('');
  return`<article class="area-summary-card ${area}"><header><i data-lucide="${areaInfo.icon}"></i><h3>${areaInfo.label}</h3></header><div class="area-metrics">${metricCharts}</div></article>`;
}
function legacyAreaDashboardHtml(area,records){
  const info={recepcion:{label:'Recepción',icon:'package-open',formula:'Rechazados + en auditoría respecto de agendados'},preparacion:{label:'Preparación',icon:'boxes',formula:'Avance procesado respecto de líneas asignadas'},despacho:{label:'Despacho',icon:'truck',formula:'Despachado respecto del total asignado'}}[area],values=key=>records.map(record=>record.metrics?.[key]?.[area]??null),advance=values('foco'),productivity=values('productividad'),hours=values('horas'),attendance=values('dotacion'),latest=list=>[...list].reverse().find(value=>value!==null)??0,shift=index=>shiftForCut(records[index].cut)?.id||'noche',format=value=>value===null?'—':`${Math.round(value)}%`,sessionTiles=(list,type)=>list.map((value,index)=>`<div class="dashboard-session ${shift(index)} ${type}" style="--level:${Math.max(0,Math.min(100,value??0))}"><small>${records[index].cut}</small><b>${format(value)}</b><i></i></div>`).join(''),maxProductivity=Math.max(10,...productivity.filter(value=>value!==null).map(value=>Math.abs(value)));
  const productivityBars=productivity.map((value,index)=>`<div class="productivity-column ${shift(index)} ${value<0?'negative':'positive'}"><b>${value===null?'—':value.toFixed(1)}</b><div class="productivity-track"><i style="height:${value===null?0:Math.max(3,Math.abs(value)/maxProductivity*48)}%"></i></div><small>${records[index].cut}</small></div>`).join(''),hoursHeat=hours.map((value,index)=>`<div class="heat-cell ${shift(index)}" style="--heat:${(value??0)/100}"><small>${records[index].cut}</small><b>${format(value)}</b><span>${value===null?'Sin datos':value>=80?'Óptimo':value>=50?'Medio':'Bajo'}</span></div>`).join(''),attendanceBars=attendance.map((value,index)=>`<div class="attendance-column ${shift(index)}"><b>${format(value)}</b><div><i style="height:${Math.max(0,Math.min(100,value??0))}%"></i></div><small>${records[index].cut}</small></div>`).join('');
  return`<section class="area-dashboard"><article class="dashboard-panel advance-panel"><header><span><i data-lucide="target"></i><b>Avance operacional</b></span><small>${info.formula}</small></header><div class="advance-body"><div class="progress-ring" style="--progress:${latest(advance)}"><div><b>${Math.round(latest(advance))}%</b><small>último registro</small></div></div><div class="session-strip">${sessionTiles(advance,'advance')}</div></div></article><article class="dashboard-panel productivity-panel"><header><span><i data-lucide="gauge"></i><b>Productividad</b></span><small>Variación promedio por sesión</small></header><div class="productivity-bars">${productivityBars}</div></article><article class="dashboard-panel hours-panel"><header><span><i data-lucide="clock-3"></i><b>Horas directas</b></span><small>Intensidad porcentual · máximo 100%</small></header><div class="hours-heatmap">${hoursHeat}</div></article><article class="dashboard-panel attendance-panel"><header><span><i data-lucide="users-round"></i><b>Asistencia</b></span><small>Presentes respecto de dotación total</small></header><div class="attendance-bars">${attendanceBars}</div></article></section>`;
}
function productivityDistributionHtml(records,values,shift){
  const samples=values.map((value,index)=>({value,index})).filter(sample=>Number.isFinite(sample.value));
  if(!samples.length)return'<div class="chart-empty"><i data-lucide="scatter-chart"></i><b>Sin datos de productividad</b></div>';
  const domainMin=-20,domainMax=20,curveCenter=0,curveSigma=6.5,width=620,height=184,left=42,right=602,top=15,bottom=143,clamp=value=>Math.max(domainMin,Math.min(domainMax,value)),x=value=>left+(value-domainMin)/(domainMax-domainMin)*(right-left),plotX=value=>x(clamp(value)),bellY=value=>{const density=Math.exp(-.5*((value-curveCenter)/curveSigma)**2);return bottom-density*(bottom-top-13)},curve=Array.from({length:81},(_,index)=>{const value=domainMin+(domainMax-domainMin)*index/80;return{x:x(value),y:bellY(value)}}),curveLine=curve.map((point,index)=>`${index?'L':'M'}${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' '),curveArea=`M${curve[0].x.toFixed(1)},${bottom} ${curve.map(point=>`L${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' ')} L${curve[curve.length-1].x.toFixed(1)},${bottom} Z`,references=[-20,-10,0,10,20],referenceLines=references.map(value=>`<line class="distribution-reference${value===0?' center':''}" x1="${x(value)}" y1="${top}" x2="${x(value)}" y2="${bottom}"/><text class="distribution-reference-label" x="${x(value)}" y="171" text-anchor="middle">${value}</text>`).join('');
  const dots=samples.map((sample,order)=>{const colorShift=shift(sample.index),cx=plotX(sample.value),cy=samples.length===1?bottom-28:bottom-12-order*(bottom-top-39)/(samples.length-1),nearLeft=cx<x(-16),nearRight=cx>x(16),anchor=nearLeft?'start':nearRight?'end':'middle',labelX=cx+(nearLeft?7:nearRight?-7:0),cut=records[sample.index].cut,valueLabel=`${sample.value>0?'+':''}${sample.value.toFixed(0)}`;return`<g class="distribution-point ${colorShift}"><circle cx="${cx}" cy="${cy.toFixed(1)}" r="5"><title>${cut}: ${sample.value.toFixed(1)}</title></circle><text class="distribution-point-label" x="${labelX}" y="${Math.max(12,cy-8).toFixed(1)}" text-anchor="${anchor}">${cut} · ${valueLabel}</text></g>`}).join('');
  return`<div class="productivity-distribution"><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" role="img" aria-label="Dispersión de productividad sobre una distribución normal fija centrada en cero, con referencias desde menos veinte hasta veinte"><defs><linearGradient id="gaussFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#43bff2" stop-opacity=".52"/><stop offset="1" stop-color="#43bff2" stop-opacity=".04"/></linearGradient></defs><path class="gaussian-area" d="${curveArea}"/>${referenceLines}<path class="gaussian-line" d="${curveLine}"/><text class="distribution-center-label" x="${x(0)}" y="${top+8}" text-anchor="middle">CENTRO FIJO · 0</text>${dots}<line class="distribution-axis-line" x1="${left}" y1="${bottom}" x2="${right}" y2="${bottom}"/></svg></div>`;
}
function hoursFlowHtml(records,values,shift){
  const samples=values.map((value,index)=>({value,index})).filter(sample=>Number.isFinite(sample.value));
  if(!samples.length)return'<div class="chart-empty"><i data-lucide="activity"></i><b>Sin datos de horas directas</b></div>';
  const width=620,height=184,left=42,right=602,top=15,bottom=143,x=index=>left+(right-left)*index/(cuts.length-1),y=value=>top+(100-Math.max(0,Math.min(100,value)))/100*(bottom-top),segments=[];let current=[];
  values.forEach((value,index)=>{if(Number.isFinite(value))current.push({value,index});else if(current.length){segments.push(current);current=[]}});if(current.length)segments.push(current);
  const paths=segments.map(segment=>{const line=segment.map((point,index)=>`${index?'L':'M'}${x(point.index).toFixed(1)},${y(point.value).toFixed(1)}`).join(' '),last=segment[segment.length-1],area=`M${x(segment[0].index).toFixed(1)},${bottom} ${segment.map(point=>`L${x(point.index).toFixed(1)},${y(point.value).toFixed(1)}`).join(' ')} L${x(last.index).toFixed(1)},${bottom} Z`;return`<path class="hours-flow-area" d="${area}"/><path class="hours-flow-line" d="${line}"/>`}).join(''),dots=samples.map(sample=>`<g class="hours-flow-point ${shift(sample.index)}"><circle cx="${x(sample.index)}" cy="${y(sample.value)}" r="5"><title>${records[sample.index].cut}: ${Math.round(sample.value)}%</title></circle><text x="${x(sample.index)}" y="${Math.max(12,y(sample.value)-8)}" text-anchor="middle">${Math.round(sample.value)}%</text></g>`).join(''),labels=records.map((record,index)=>`<text class="hours-flow-hour" x="${x(index)}" y="172" text-anchor="middle">${record.cut}</text>`).join(''),grid=[0,50,80,100].map(value=>`<line x1="${left}" y1="${y(value)}" x2="${right}" y2="${y(value)}"/><text x="${left-7}" y="${y(value)+4}" text-anchor="end">${value}</text>`).join('');
  return`<div class="hours-flow"><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" role="img" aria-label="Ruta de intensidad de horas directas"><defs><linearGradient id="hoursFlowFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffd23f" stop-opacity=".58"/><stop offset="1" stop-color="#43bff2" stop-opacity=".05"/></linearGradient></defs><rect class="hours-target-zone" x="${left}" y="${y(100)}" width="${right-left}" height="${y(80)-y(100)}"/><text class="hours-target-label" x="${right-4}" y="${y(80)-5}" text-anchor="end">ZONA OBJETIVO ≥ 80%</text><g class="hours-flow-grid">${grid}</g>${paths}${dots}${labels}</svg></div>`;
}
function areaDashboardHtml(area,records){
  const values=key=>records.map(record=>record.metrics?.[key]?.[area]??null),productivity=values('productividad'),hours=values('horas'),attendance=values('dotacion'),shift=index=>shiftForCut(records[index].cut)?.id||'noche',format=value=>value===null?'—':`${Math.round(value)}%`,valid=list=>list.filter(Number.isFinite),average=list=>valid(list).length?valid(list).reduce((total,value)=>total+value,0)/valid(list).length:null,productivityMean=average(productivity),productivitySigma=productivityMean===null?null:Math.sqrt(valid(productivity).reduce((total,value)=>total+(value-productivityMean)**2,0)/valid(productivity).length),hoursAverage=average(hours);
  const shiftNames={noche:'Turno noche',manana:'Turno mañana',tarde:'Turno tarde'},shiftOrder=['noche','manana','tarde'],cubeValues=shiftOrder.map(shiftId=>{const meetings=records.map((record,index)=>({shiftId:shift(index),productivity:productivity[index],hours:hours[index],attendance:attendance[index]})).filter(meeting=>meeting.shiftId===shiftId&&meeting.productivity!==null&&meeting.hours!==null&&meeting.attendance!==null),results=meetings.map(meeting=>Math.max(0,100+meeting.productivity)/100*(meeting.hours/100)*(meeting.attendance/100)*100),average=results.length?results.reduce((total,value)=>total+value,0)/results.length:null;return{shiftId,average,count:results.length}}),cubeCards=cubeValues.map(item=>`<div class="shift-cube-card ${item.shiftId}"><div class="shift-cube" style="--cube-level:${Math.max(0,Math.min(100,item.average??0))}%" aria-label="${shiftNames[item.shiftId]}; desempeño ${format(item.average)}"><span class="cube-face cube-front"><b>${format(item.average)}</b></span><span class="cube-face cube-top"></span><span class="cube-face cube-side"></span></div><strong>${shiftNames[item.shiftId]}</strong><small>${item.count?`${item.count} reunión${item.count===1?'':'es'} promediada${item.count===1?'':'s'}`:'Sin reuniones completas'}</small></div>`).join('');
  const attendanceBars=attendance.map((value,index)=>`<div class="attendance-column ${shift(index)}"><b>${format(value)}</b><div><i style="height:${Math.max(0,Math.min(100,value??0))}%"></i></div><small>${records[index].cut}</small></div>`).join('');
  return`<section class="area-dashboard"><article class="dashboard-panel performance-panel"><header><span><i data-lucide="box"></i><b>Desempeño por turno</b></span><small>(100% + variación) × horas directas × asistencia</small></header><div class="shift-cubes">${cubeCards}</div></article><article class="dashboard-panel productivity-panel distribution-panel"><header><span><i data-lucide="scatter-chart"></i><b>Productividad</b></span><small>${productivityMean===null?'Sin reuniones guardadas':`Campana fija en 0 · promedio ${productivityMean.toFixed(1)} · σ ${productivitySigma.toFixed(1)}`}</small></header>${productivityDistributionHtml(records,productivity,shift)}</article><article class="dashboard-panel hours-panel flow-panel"><header><span><i data-lucide="activity"></i><b>Horas directas</b></span><small>${hoursAverage===null?'Sin reuniones guardadas':`Ruta de intensidad · promedio ${Math.round(hoursAverage)}%`}</small></header>${hoursFlowHtml(records,hours,shift)}</article><article class="dashboard-panel attendance-panel"><header><span><i data-lucide="users-round"></i><b>Asistencia</b></span><small>Presentes respecto de dotación total</small></header><div class="attendance-bars">${attendanceBars}</div></article></section>`;
}
function renderSummary(){
  const view=document.querySelector('#summaryView'),records=summarySnapshots().map(item=>({...item,metrics:summaryMetrics(item.snapshot)})),charts=[{key:'foco',title:'Avance operacional',description:'Recepción: rechazados + auditoría / agendados · Preparación: avance / asignado · Despacho: despachado / asignado',unit:'%',min:0,max:100,icon:'target'},{key:'productividad',title:'Productividad por área',description:'Promedio de variación entre operativo y grúa',unit:'',min:-100,max:100,icon:'gauge'},{key:'horas',title:'Horas directas por área',description:'Porcentaje promedio de operativo y grúa · máximo 100%',unit:'%',min:0,max:100,icon:'clock-3'},{key:'dotacion',title:'Asistencia de dotación',description:'Asistencia real respecto de la dotación total',unit:'%',min:0,max:100,icon:'users-round'}];
  const available=records.filter(record=>record.snapshot),complete=available.filter(record=>record.snapshot.validation?.valid||record.snapshot.completed).length;
  view.querySelector('.summary-content').innerHTML=`<div class="summary-overview"><span><b>${available.length}</b> sesiones registradas</span><span><b>${complete}</b> completas</span><div class="summary-legend"><i class="noche"></i>Noche<i class="manana"></i>Mañana<i class="tarde"></i>Tarde</div></div><nav class="area-tabs">${Object.entries({recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'}).map(([area,label])=>`<button class="${area===activeSummaryArea?'active':''}" data-summary-area="${area}">${label}</button>`).join('')}</nav>${areaDashboardHtml(activeSummaryArea,records)}`;
  view.querySelectorAll('[data-summary-area]').forEach(button=>button.addEventListener('click',()=>{activeSummaryArea=button.dataset.summaryArea;renderSummary()}));
  window.lucide?.createIcons();
}
function initializeSummary(){
  const view=document.createElement('main');view.id='summaryView';view.className='summary-view';view.innerHTML='<header class="summary-header"><div><i data-lucide="chart-no-axes-combined"></i><span><small>AVANCE ACUMULADO</small><h2>Resumen del día</h2></span></div><button id="closeSummary" type="button"><i data-lucide="arrow-left"></i>Volver al tablero</button></header><section class="summary-content"></section>';document.querySelector('.board').insertAdjacentElement('afterend',view);
  const closeButton=view.querySelector('#closeSummary');document.querySelector('.logo-box').insertAdjacentElement('afterend',closeButton);const open=()=>{closeCalculators();closeClearPanel();renderSummary();document.body.classList.add('summary-open');history.replaceState(null,'','#resumen')},close=()=>{document.body.classList.remove('summary-open');history.replaceState(null,'',location.pathname+location.search)},trigger=document.querySelector('.summary-access-card');trigger.innerHTML='<header><h2><i data-lucide="badge-check"></i>OMS</h2><img class="oms-header-logo" src="oms-first-choice.png" alt=""></header><button id="openSummary" type="button" title="Ver resumen gráfico del día"><span class="oms-cube-title">CUBO GLOBAL</span><span class="oms-daily-cube" aria-hidden="true"><span class="oms-cube-top"></span><span class="oms-cube-side"></span><span class="oms-cube-front"><b>—</b></span></span></button>';trigger.querySelector('button').addEventListener('click',open);closeButton.addEventListener('click',close);paintOmsCube();if(location.hash==='#resumen')open();
}
function initializeCutNavToggle(){const nav=document.querySelector('.cut-nav'),label=nav?.querySelector(':scope>span');if(!nav||!label)return;const button=document.createElement('button');button.type='button';button.className='cut-nav-toggle';button.innerHTML='<span>Avance del día</span><i data-lucide="chevron-up"></i>';button.setAttribute('aria-label','Ocultar turnos');button.setAttribute('aria-expanded','true');label.replaceWith(button);const paint=collapsed=>{document.body.classList.toggle('cut-nav-collapsed',collapsed);button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Mostrar turnos':'Ocultar turnos');button.querySelector('span').textContent=collapsed?'Mostrar turnos':'Avance del día';button.querySelector('svg,i')?.setAttribute('data-lucide',collapsed?'chevron-down':'chevron-up');window.lucide?.createIcons();localStorage.setItem('dhl-turnos-colapsados',String(collapsed))};button.addEventListener('click',()=>paint(!document.body.classList.contains('cut-nav-collapsed')));paint(localStorage.getItem('dhl-turnos-colapsados')==='true')}
function initializeCarouselMode(){
  const button=document.querySelector('#carouselMode');if(!button)return;const areas=['recepcion','preparacion','despacho'],delay=8000;let timer=null,step=0;
  const show=current=>{if(current===0){document.body.classList.remove('summary-open');history.replaceState(null,'',location.pathname+location.search)}else{activeSummaryArea=areas[current-1];renderSummary();document.body.classList.add('summary-open');history.replaceState(null,'','#resumen')}};
  const paint=running=>{document.body.classList.toggle('carousel-running',running);button.setAttribute('aria-pressed',String(running));button.innerHTML=`<i data-lucide="${running?'square':'gallery-horizontal-end'}"></i><span>${running?'Detener':'Carrusel'}</span>`;button.setAttribute('aria-label',running?'Detener modo carrusel':'Iniciar modo carrusel');window.lucide?.createIcons()};
  const stop=()=>{if(timer)clearInterval(timer);timer=null;paint(false)},start=()=>{step=document.body.classList.contains('summary-open')?Math.max(1,areas.indexOf(activeSummaryArea)+1):0;paint(true);timer=setInterval(()=>{step=(step+1)%4;show(step)},delay)};
  button.addEventListener('click',()=>timer?stop():start());document.querySelector('#closeSummary')?.addEventListener('click',stop);paint(false);
}

function sanitizeNotePoint(point){return{x:Math.max(0,Math.min(1,Number(point?.x)||0)),y:Math.max(0,Math.min(1,Number(point?.y)||0)),p:Math.max(.1,Math.min(1,Number(point?.p)||.5))}}
function readPersistentNotes(){
  let stored=null;try{stored=JSON.parse(localStorage.getItem(NOTES_STORAGE_KEY)||'null')}catch{stored=null}
  const strokes=Array.isArray(stored?.strokes)?stored.strokes.slice(-800).map(stroke=>({tool:stroke?.tool==='eraser'?'eraser':'pen',width:Math.max(1,Math.min(80,Number(stroke?.width)||4)),points:Array.isArray(stroke?.points)?stroke.points.slice(0,4000).map(sanitizeNotePoint):[]})).filter(stroke=>stroke.points.length):[];
  persistentNotes={strokes,updatedAt:strokes.length?stored?.updatedAt||null:null};return persistentNotes;
}
function notesHaveContent(){return persistentNotes.strokes.length>0}
function updateNotesBadge(){const badge=document.querySelector('#notesBadge');if(!badge)return;badge.hidden=!notesHaveContent();badge.textContent='';document.querySelector('#openNotes')?.classList.toggle('has-notes',notesHaveContent())}
function paintNotesStatus(message='Guardado automático permanente',error=false){const status=document.querySelector('#notesSavedStatus');if(!status)return;status.textContent=message;status.classList.toggle('error',error)}
function persistNotesNow(message='Notas guardadas'){
  persistentNotes.updatedAt=new Date().toISOString();
  try{localStorage.setItem(NOTES_STORAGE_KEY,JSON.stringify(persistentNotes));paintNotesStatus(message)}catch{paintNotesStatus('No se pudieron guardar las notas',true)}
  updateNotesBadge();
}
function drawNoteStroke(context,stroke,width,height){
  if(!stroke.points.length)return;context.save();context.globalCompositeOperation=stroke.tool==='eraser'?'destination-out':'source-over';context.strokeStyle='#102e43';context.fillStyle='#102e43';context.lineCap='round';context.lineJoin='round';context.lineWidth=stroke.width;
  const points=stroke.points;if(points.length===1){const point=points[0];context.beginPath();context.arc(point.x*width,point.y*height,stroke.width/2,0,Math.PI*2);context.fill()}else{context.beginPath();context.moveTo(points[0].x*width,points[0].y*height);for(let index=1;index<points.length;index++)context.lineTo(points[index].x*width,points[index].y*height);context.stroke()}context.restore();
}
function drawNotesCanvas(){
  const canvas=document.querySelector('#notesCanvas');if(!canvas||canvas.closest('[hidden]'))return;const rect=canvas.getBoundingClientRect();if(rect.width<2||rect.height<2)return;const ratio=Math.min(window.devicePixelRatio||1,2),pixelWidth=Math.round(rect.width*ratio),pixelHeight=Math.round(rect.height*ratio);if(canvas.width!==pixelWidth||canvas.height!==pixelHeight){canvas.width=pixelWidth;canvas.height=pixelHeight}const context=canvas.getContext('2d');context.setTransform(ratio,0,0,ratio,0,0);context.clearRect(0,0,rect.width,rect.height);persistentNotes.strokes.forEach(stroke=>drawNoteStroke(context,stroke,rect.width,rect.height));document.querySelector('#notesCanvasHint')?.toggleAttribute('hidden',persistentNotes.strokes.length>0);
}
function canvasNotePoint(event,canvas){const rect=canvas.getBoundingClientRect();return sanitizeNotePoint({x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height,p:event.pressure||.5})}
function setNotesTool(tool){notesTool=tool==='eraser'?'eraser':'pen';document.querySelectorAll('[data-notes-tool]').forEach(button=>{const active=button.dataset.notesTool===notesTool;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});document.querySelector('#notesCanvas')?.classList.toggle('eraser-active',notesTool==='eraser')}
function openNotesPanel(){closeCalculators();closeClearPanel();closeCapturePreview();const backdrop=document.querySelector('#notesBackdrop');backdrop.classList.add('open');backdrop.setAttribute('aria-hidden','false');document.body.classList.add('notes-open');paintNotesStatus(persistentNotes.updatedAt?'Notas guardadas':'Guardado automático permanente');window.lucide?.createIcons();requestAnimationFrame(drawNotesCanvas)}
function closeNotesPanel(){const backdrop=document.querySelector('#notesBackdrop');if(!backdrop)return;if(activeNoteStrokes.size)persistNotesNow();backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true');document.body.classList.remove('notes-open');activeNoteStrokes.clear()}
function initializePersistentNotes(){
  readPersistentNotes();const canvas=document.querySelector('#notesCanvas');if(!canvas)return;updateNotesBadge();setNotesTool('pen');
  document.querySelector('#openNotes')?.addEventListener('click',openNotesPanel);document.querySelector('#closeNotes')?.addEventListener('click',closeNotesPanel);document.querySelectorAll('[data-notes-tool]').forEach(button=>button.addEventListener('click',()=>setNotesTool(button.dataset.notesTool)));
  canvas.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;const stroke={tool:notesTool,width:notesTool==='eraser'?34:4,points:[canvasNotePoint(event,canvas)]};persistentNotes.strokes.push(stroke);if(persistentNotes.strokes.length>800)persistentNotes.strokes.splice(0,persistentNotes.strokes.length-800);activeNoteStrokes.set(event.pointerId,stroke);try{canvas.setPointerCapture(event.pointerId)}catch{}drawNotesCanvas();updateNotesBadge();event.preventDefault()});
  canvas.addEventListener('pointermove',event=>{const stroke=activeNoteStrokes.get(event.pointerId);if(!stroke)return;const point=canvasNotePoint(event,canvas),previous=stroke.points[stroke.points.length-1];if(Math.hypot(point.x-previous.x,point.y-previous.y)>.0015&&stroke.points.length<4000){stroke.points.push(point);drawNotesCanvas()}event.preventDefault()});
  const finishStroke=event=>{if(!activeNoteStrokes.has(event.pointerId))return;activeNoteStrokes.delete(event.pointerId);persistNotesNow();event.preventDefault()};canvas.addEventListener('pointerup',finishStroke);canvas.addEventListener('pointercancel',finishStroke);
  document.querySelector('#undoNoteStroke')?.addEventListener('click',()=>{persistentNotes.strokes.pop();drawNotesCanvas();persistNotesNow('Último trazo eliminado')});
  document.querySelector('#clearNotes')?.addEventListener('click',()=>{activeNoteStrokes.clear();persistentNotes={strokes:[],updatedAt:null};drawNotesCanvas();persistNotesNow('Pizarra de notas limpia')});
  window.addEventListener('resize',()=>{if(document.querySelector('#notesBackdrop')?.classList.contains('open'))drawNotesCanvas()});window.addEventListener('storage',event=>{if(event.key!==NOTES_STORAGE_KEY)return;readPersistentNotes();updateNotesBadge();drawNotesCanvas()});
}

function showToolMessage(message,error=false){const toast=document.querySelector('#toolToast');if(!toast)return;toast.textContent=message;toast.classList.toggle('error',error);toast.classList.add('show');clearTimeout(showToolMessage.timer);showToolMessage.timer=setTimeout(()=>toast.classList.remove('show'),4500)}
function canvasToPng(canvas){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('No se pudo crear el PNG')),'image/png'))}
function screenshotFilename(){const now=new Date(),date=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago'}).format(now),time=new Intl.DateTimeFormat('es-CL',{timeZone:'America/Santiago',hour:'2-digit',minute:'2-digit',hour12:false}).format(now).replace(':','-');return`dialogo-tactico-${date}-${time}.png`}
function screenshotFile(blob,filename){try{return new File([blob],filename,{type:'image/png',lastModified:Date.now()})}catch{blob.name=filename;return blob}}
function canShareScreenshot(file){if(typeof navigator.share!=='function')return false;if(typeof navigator.canShare!=='function')return true;try{return navigator.canShare({files:[file]})}catch{return false}}
function prepareCaptureProcessLabels(){const items=[...document.querySelectorAll('.process-label')].map(container=>{const source=container.querySelector('b'),rect=container.getBoundingClientRect(),visibility=source.style.visibility;source.style.visibility='hidden';return{text:source.textContent,rect,restore:()=>{source.style.visibility=visibility}}});return{items,restore:()=>items.forEach(item=>item.restore())}}
function paintCaptureProcessLabels(canvas,items){const context=canvas.getContext('2d');context.save();context.fillStyle='#ffffff';context.font='800 8px "Barlow Condensed", "Arial Narrow", sans-serif';context.textAlign='center';context.textBaseline='middle';items.forEach(item=>context.fillText(item.text,item.rect.left+item.rect.width/2,item.rect.top+item.rect.height*.55,Math.max(12,item.rect.width-5)));context.restore()}
async function createDashboardScreenshot(){
  if(typeof window.html2canvas!=='function')throw new Error('El capturador no está disponible');await document.fonts?.ready;const processLabels=prepareCaptureProcessLabels();document.body.classList.add('capture-rendering');void document.body.offsetHeight;try{const canvas=await window.html2canvas(document.body,{backgroundColor:'#061f35',logging:false,useCORS:true,scale:1,width:window.innerWidth,height:window.innerHeight,windowWidth:window.innerWidth,windowHeight:window.innerHeight,scrollX:0,scrollY:0,ignoreElements:element=>element.hasAttribute?.('data-html2canvas-ignore')});paintCaptureProcessLabels(canvas,processLabels.items);const blob=await canvasToPng(canvas),filename=screenshotFilename();return{blob,file:screenshotFile(blob,filename),filename,width:canvas.width,height:canvas.height}}finally{document.body.classList.remove('capture-rendering');processLabels.restore()}
}
function closeCapturePreview(){const backdrop=document.querySelector('#capturePreview');if(!backdrop)return;backdrop.classList.remove('open');backdrop.setAttribute('aria-hidden','true')}
function openCapturePreview(capture){
  if(lastScreenshotUrl)URL.revokeObjectURL(lastScreenshotUrl);lastScreenshot=capture;lastScreenshotUrl=URL.createObjectURL(capture.blob);const image=document.querySelector('#captureImage'),share=document.querySelector('#shareCapture'),help=document.querySelector('#captureHelp');image.src=lastScreenshotUrl;const nativeAvailable=canShareScreenshot(capture.file);share.hidden=!nativeAvailable;help.textContent=nativeAvailable?'Elige Bluetooth en el menú nativo de la TV.':'Esta TV no ofrece compartir archivos desde la PWA. Puedes guardar el PNG.';document.querySelector('#capturePreview').classList.add('open');document.querySelector('#capturePreview').setAttribute('aria-hidden','false');window.lucide?.createIcons();return nativeAvailable;
}
async function shareScreenshot(capture=lastScreenshot){if(!capture||!canShareScreenshot(capture.file))throw new Error('Compartir archivos no está disponible');await navigator.share({title:'Diálogo Táctico DHL',files:[capture.file]})}
function downloadScreenshot(){if(!lastScreenshot)return;const link=document.createElement('a');link.href=lastScreenshotUrl;link.download=lastScreenshot.filename;link.rel='noopener';document.body.append(link);link.click();link.remove();showToolMessage('Captura guardada como PNG')}
async function minimizeShiftMenuForCapture(){if(document.body.classList.contains('cut-nav-collapsed'))return;document.querySelector('.cut-nav-toggle')?.click();await new Promise(resolve=>setTimeout(resolve,280))}
async function captureAndShareView(){
  if(capturingView)return;capturingView=true;const button=document.querySelector('#captureView'),label=button?.querySelector('span');closeCalculators();closeClearPanel();closeNotesPanel();closeCapturePreview();document.activeElement?.blur();if(button){button.disabled=true;button.classList.add('busy')}if(label)label.textContent='Capturando…';
  try{await minimizeShiftMenuForCapture();const capture=await createDashboardScreenshot(),nativeAvailable=openCapturePreview(capture);if(nativeAvailable){try{await shareScreenshot(capture);closeCapturePreview();showToolMessage('Captura enviada al menú de compartir')}catch(error){if(error?.name!=='AbortError')document.querySelector('#captureHelp').textContent='Pulsa Compartir para abrir el menú nativo y elegir Bluetooth.'}}else showToolMessage('Captura lista para guardar')}
  catch(error){showToolMessage(error?.message||'No se pudo capturar la vista',true)}finally{capturingView=false;if(button){button.disabled=false;button.classList.remove('busy')}if(label)label.textContent='Captura'}
}
function initializeCaptureTools(){
  document.querySelector('#captureView')?.addEventListener('click',captureAndShareView);document.querySelector('#closeCapturePreview')?.addEventListener('click',closeCapturePreview);document.querySelector('#downloadCapture')?.addEventListener('click',downloadScreenshot);document.querySelector('#shareCapture')?.addEventListener('click',async()=>{try{await shareScreenshot();closeCapturePreview();showToolMessage('Captura compartida')}catch(error){if(error?.name!=='AbortError')showToolMessage('La TV no pudo abrir el menú de compartir',true)}});window.addEventListener('beforeunload',()=>{if(lastScreenshotUrl)URL.revokeObjectURL(lastScreenshotUrl)});document.addEventListener('keydown',event=>{if(!['Escape','BrowserBack'].includes(event.key))return;if(document.querySelector('#capturePreview')?.classList.contains('open')){event.preventDefault();closeCapturePreview()}else if(document.querySelector('#notesBackdrop')?.classList.contains('open')){event.preventDefault();closeNotesPanel()}});
}
function initializeCriticalControlIcons(){const card=document.querySelector('.hse-card'),button=card?.querySelector('.hse-view-toggle');if(!button)return;const paint=()=>button.innerHTML=controlIcon(card.classList.contains('show-prevention')?'calendar':'gauge');button.addEventListener('click',()=>queueMicrotask(paint));paint()}
document.querySelector('#clearData').addEventListener('click',()=>{const panel=document.querySelector('#clearAreas'),open=panel.classList.toggle('open');if(!open)closeClearPanel();else panel.setAttribute('aria-hidden','false')});
document.querySelectorAll('[data-clear-area]').forEach(button=>button.addEventListener('click',()=>{selectedClearArea=button.dataset.clearArea;document.querySelector('#selectedClearArea').textContent=`2 · ${areaNames[selectedClearArea]}: ¿qué sección?`;document.querySelector('#clearAreas').classList.add('choose-section')}));
document.querySelectorAll('[data-clear-section]').forEach(button=>button.addEventListener('click',()=>{if(selectedClearArea)clearSection(selectedClearArea,button.dataset.clearSection)}));
document.querySelector('#clearAll').addEventListener('click',clearEverything);
document.querySelector('.clear-back').addEventListener('click',()=>{selectedClearArea=null;document.querySelector('#clearAreas').classList.remove('choose-section')});
document.querySelector('.clear-cancel').addEventListener('click',closeClearPanel);
function addSemanticIcons(){
  const columnIcons=['target','gauge','clock-3','users-round'];document.querySelectorAll('.column-head:not(.blank)').forEach((header,index)=>header.querySelector('b')?.insertAdjacentHTML('afterbegin',`<i data-lucide="${columnIcons[index]}"></i>`));
  const processIcons=['package-open','boxes','truck'];document.querySelectorAll('.process-label').forEach((label,index)=>label.insertAdjacentHTML('afterbegin',`<i class="process-icon" data-lucide="${processIcons[index]}"></i>`));
  document.querySelectorAll('.side-card header h2').forEach(heading=>heading.insertAdjacentHTML('afterbegin',`<i data-lucide="${heading.textContent.includes('QRA')?'clipboard-check':'shield-check'}"></i>`));
  document.querySelectorAll('.data-card h2').forEach(heading=>{const text=heading.textContent.toLowerCase();const icon=text.includes('agenda')?'calendar-check':text.includes('líneas')?'list-checks':text.includes('planificación')?'route':text.includes('variación')?'chart-no-axes-combined':text.includes('horas')?'timer':'users';heading.insertAdjacentHTML('afterbegin',`<i data-lucide="${icon}"></i>`)});
  const side=document.querySelector('.side-panel'),cards=[...side.children];if(cards.length===3)side.replaceChildren(cards[2],cards[0],cards[1]);
}
function init(){initializeAreaMetadata();initializeExpectedKilos();initializePersistentNotes();initializeCaptureTools();syncSafetyCounter();syncQraState();initialSnapshot=getSnapshot();activeDate=todayKey();dailyRecord=readDailyRecord();expectedKilos={in:sanitizeExpectedKilos(dailyRecord.expectedKilos?.in),out:sanitizeExpectedKilos(dailyRecord.expectedKilos?.out)};dailyRecord.expectedKilos=structuredClone(expectedKilos);paintExpectedKilos();const latest=[...Object.values(dailyRecord.sessions),...Object.values(dailyRecord.drafts)].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))[0];applySnapshot(blankSnapshot(cuts[0]));renderInlineCrew();loadMeeting(latest?.cut||cuts[0]);paintMeetingStates();addSemanticIcons();initializeBusinessLineSelector();initializeQraRadar();initializeHsePrevention();initializeCriticalControlIcons();initializeSummary();initializeCarouselMode();initializeCutNavToggle();bindDraggableClearPanel();paintSystemDate();window.lucide?.createIcons();setInterval(checkDayChange,60000);setInterval(paintSystemDate,1000)}
init();window.addEventListener('pagehide',persistCurrentDraft);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persistCurrentDraft();else paintSystemDate()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
