const prepLines=['BISE','MINERÍA','WALMART','FACILITY'],dispatchLines=['BISE','MINERÍA','WALMART','WALMART RM','FACILITY'];
const prep=[[600,400,67],[450,310,69],[700,520,74],[280,190,68]],dispatch=[[280,170,130,92],[210,140,98,75],[340,215,160,118],[0,0,0,0],[150,80,62,41]];
prepLines.splice(3,0,'WLM RM');prep.splice(3,0,[0,0,0]);dispatchLines[3]='WLM RM';
const shifts=[{id:'noche',label:'Turno noche',cuts:['01:00','03:00','05:00']},{id:'manana',label:'Turno mañana',cuts:['09:00','11:00','13:00']},{id:'tarde',label:'Turno tarde',cuts:['17:00','19:00','21:00']}],cuts=shifts.flatMap(shift=>shift.cuts);
document.querySelector('.heading span').textContent='Operación · CD Aramark';
const areaNames={recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'},roleNames={operativo:'operativo',grua:'grúa'};
const JSON_STORAGE_KEY='dhl-reuniones-diarias-json';
const HSE_STORAGE_KEY='dhl-hse-dias-sin-accidentes';
const PREVENTION_STORAGE_KEY='dhl-hse-indice-prevencion';
const QRA_STORAGE_KEY='dhl-qra-5s-persistente';
const BUSINESS_LINES_STORAGE_KEY='dhl-lineas-negocio-visibles',businessLines=[...dispatchLines];
const controlIcon=name=>({
  list:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 6h11M9 12h11M9 18h11"/><circle cx="4" cy="6" r="1"/><circle cx="4" cy="12" r="1"/><circle cx="4" cy="18" r="1"/></svg>',
  radar:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 3v18M3 12h18"/><circle cx="15" cy="9" r="1.5" class="icon-fill"/></svg>',
  filter:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M7 12h10M10 18h4"/></svg>',
  calendar:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M8 14h2M14 14h2M8 18h2"/></svg>',
  gauge:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 18a8 8 0 1 1 16 0M12 18l5-7"/><circle cx="12" cy="18" r="1.5" class="icon-fill"/></svg>'
}[name]||'');
let selectedTransfer=null,dragState=null,lastMove=null,toastTimer=null,initialSnapshot=null,dailyRecord=null,dirty=false,activeDate='',selectedClearArea=null,activeSummaryArea='recepcion',refreshBusinessLineFilters=()=>{};
let crew={recepcion:{operativo:88,grua:20,planOperativo:92,planGrua:22},preparacion:{operativo:42,grua:12,planOperativo:45,planGrua:12},despacho:{operativo:31,grua:9,planOperativo:33,planGrua:10}};
let crewEntered={recepcion:{operativo:false,grua:false},preparacion:{operativo:false,grua:false},despacho:{operativo:false,grua:false}};
const emptyTransferBalance=()=>({recepcion:{operativo:0,grua:0},preparacion:{operativo:0,grua:0},despacho:{operativo:0,grua:0}});let transferBalance=emptyTransferBalance();
function settleTransfers(){Object.keys(crew).forEach(area=>['operativo','grua'].forEach(role=>crew[area][role]=Math.max(0,crew[area][role]-(transferBalance[area]?.[role]||0))));transferBalance=emptyTransferBalance()}

document.querySelector('#prepRows').innerHTML=prepLines.map((line,index)=>`<tr data-business-line="${line}"><td>${line}</td>${prep[index].map((value,column)=>`<td class="editable-cell ${column===2?'prep-advance':''}">${value}</td>`).join('')}</tr>`).join('');
document.querySelector('#dispatchRows').innerHTML=dispatchLines.map((line,index)=>`<tr data-business-line="${line}"><td>${line}</td>${dispatch[index].map(value=>`<td class="editable-cell">${value}</td>`).join('')}</tr>`).join('');
document.querySelector('#cutList').innerHTML=shifts.map((shift,shiftIndex)=>`<section class="shift-group ${shift.id}"><span>${shift.label}</span><div class="shift-times">${shift.cuts.map((cut,index)=>`<button type="button" class="cut-chip incomplete ${shiftIndex===0&&index===0?'active':''}" data-cut="${cut}">${cut}</button>`).join('')}</div></section>`).join('');

const personIcon='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7 8.2c0-3.5-3.1-6.2-7-6.2s-7 2.7-7 6.2V22h14v-1.8Z"/></svg>';
function renderInlineCrew(){
  document.querySelectorAll('.dotacion').forEach((card,index)=>{
    const area=['recepcion','preparacion','despacho'][index],data=crew[area];card.dataset.area=area;
    card.querySelector('.attendance').outerHTML=`<div class="inline-workforce">
      <div class="workforce-role" data-role="operativo"><span>Operativos</span><div class="workforce-fields"><button class="workforce-numbers" data-field="operativo" data-label="Operativos que asistieron"><small>Asistió</small><strong>${data.operativo}</strong></button><button class="workforce-numbers" data-field="planOperativo" data-label="Dotación total de operativos"><small>Dotación total</small><strong>${data.planOperativo}</strong></button></div><button class="person-handle" data-origin="${area}" data-role="operativo" aria-label="Mover una persona operativa desde ${areaNames[area]}">${personIcon}</button></div>
      <div class="workforce-role" data-role="grua"><span>Grúas</span><div class="workforce-fields"><button class="workforce-numbers" data-field="grua" data-label="Grúas que asistieron"><small>Asistió</small><strong>${data.grua}</strong></button><button class="workforce-numbers" data-field="planGrua" data-label="Dotación total de grúas"><small>Dotación total</small><strong>${data.planGrua}</strong></button></div><button class="person-handle" data-origin="${area}" data-role="grua" aria-label="Mover una grúa desde ${areaNames[area]}">${personIcon}</button></div>
    </div>`;
  });document.querySelectorAll('.workforce-numbers').forEach(element=>element.addEventListener('click',openEditor));bindInlineCrew();
}
function updateTransferBadges(){document.querySelectorAll('.person-handle').forEach(button=>{let badge=button.querySelector('.transfer-balance');if(!badge){badge=document.createElement('small');badge.className='transfer-balance';button.append(badge)}const value=transferBalance[button.dataset.origin]?.[button.dataset.role]||0;badge.textContent=value>0?`+${value}`:value<0?String(value):'';badge.classList.toggle('positive',value>0);badge.classList.toggle('negative',value<0)})}
function updateInlineCounts(){document.querySelectorAll('.dotacion').forEach(card=>{const area=card.dataset.area;card.querySelectorAll('.workforce-numbers').forEach(field=>field.querySelector('strong').textContent=crew[area][field.dataset.field])});updateTransferBadges();refreshBusinessLineFilters()}
function clearDropState(){document.body.classList.remove('transfer-mode');document.querySelectorAll('.dotacion').forEach(card=>card.classList.remove('drop-ready','drop-hover'));document.querySelectorAll('.person-handle').forEach(button=>button.classList.remove('selected'));document.querySelector('#transferTip')?.classList.remove('show')}
function markDestinations(origin){document.body.classList.add('transfer-mode');document.querySelectorAll('.dotacion').forEach(card=>{if(card.dataset.area!==origin)card.classList.add('drop-ready')});document.querySelector('#transferTip')?.classList.add('show')}
function chooseTransfer(button){const sameSelection=selectedTransfer?.origin===button.dataset.origin&&selectedTransfer?.role===button.dataset.role;if(sameSelection){selectedTransfer=null;clearDropState();return}clearDropState();selectedTransfer={origin:button.dataset.origin,role:button.dataset.role};button.classList.add('selected');markDestinations(selectedTransfer.origin)}
function moveOne(origin,destination,role){
  if(!origin||!destination||origin===destination||crew[origin][role]<1)return;
  crew[origin][role]-=1;crew[destination][role]+=1;transferBalance[origin][role]-=1;transferBalance[destination][role]+=1;crewEntered[origin][role]=true;crewEntered[destination][role]=true;lastMove={origin,destination,role};selectedTransfer=null;clearDropState();updateInlineCounts();markDirty();
}
function bindInlineCrew(){
  document.querySelectorAll('.person-handle').forEach(button=>{
    button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation()});
    button.addEventListener('pointerdown',event=>{selectedTransfer=null;clearDropState();dragState={origin:button.dataset.origin,role:button.dataset.role,startX:event.clientX,startY:event.clientY,dragging:false,ghost:null};button.setPointerCapture(event.pointerId);event.preventDefault()});
    button.addEventListener('pointermove',event=>{if(!dragState)return;const distance=Math.hypot(event.clientX-dragState.startX,event.clientY-dragState.startY);if(distance>12&&!dragState.dragging){dragState.dragging=true;dragState.ghost=document.createElement('div');dragState.ghost.className='inline-drag-ghost';dragState.ghost.innerHTML=personIcon;document.body.appendChild(dragState.ghost);markDestinations(dragState.origin)}if(dragState.dragging){dragState.ghost.style.left=`${event.clientX}px`;dragState.ghost.style.top=`${event.clientY}px`;document.querySelectorAll('.dotacion').forEach(card=>card.classList.remove('drop-hover'));document.elementFromPoint(event.clientX,event.clientY)?.closest('.dotacion')?.classList.add('drop-hover')}});
    button.addEventListener('pointerup',event=>{if(!dragState)return;const state=dragState,destination=state.dragging?document.elementFromPoint(event.clientX,event.clientY)?.closest('.dotacion')?.dataset.area:null;state.ghost?.remove();dragState=null;selectedTransfer=null;clearDropState();if(state.dragging)moveOne(state.origin,destination,state.role);event.preventDefault();event.stopPropagation()});
    button.addEventListener('pointercancel',event=>{dragState?.ghost?.remove();dragState=null;selectedTransfer=null;clearDropState();event.preventDefault()});
  });
}
function showTransferToast(){
  let toast=document.querySelector('#transferToast');if(!toast){toast=document.createElement('div');toast.id='transferToast';toast.className='transfer-toast';toast.innerHTML='<span></span><button class="toast-close" aria-label="Cerrar">×</button>';document.body.appendChild(toast);toast.querySelector('.toast-close').addEventListener('click',()=>toast.classList.remove('show'))}
  toast.querySelector('span').innerHTML=`Se movió <b>1 ${roleNames[lastMove.role]}</b> de ${areaNames[lastMove.origin]} a ${areaNames[lastMove.destination]}`;requestAnimationFrame(()=>toast.classList.add('show'));clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),5000);
}
const tip=document.createElement('div');tip.id='transferTip';tip.className='transfer-tip';tip.textContent='Ahora toca el área de destino';document.body.appendChild(tip);

const allValues=()=>[...document.querySelectorAll('.stat b,.editable-cell')].filter(element=>!element.closest('.dotacion'));
const todayKey=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santiago'}).format(new Date());
const dayNumber=date=>Date.parse(`${date}T00:00:00Z`)/86400000;
function writeSafetyCounter(value){const safeValue=Math.max(0,Math.trunc(Number(value)||0));document.querySelector('.days-safe b').textContent=safeValue;localStorage.setItem(HSE_STORAGE_KEY,JSON.stringify({value:safeValue,date:todayKey()}))}
function syncSafetyCounter(simulated=false){let state;try{state=JSON.parse(localStorage.getItem(HSE_STORAGE_KEY)||'null')}catch{state=null}const today=todayKey(),initial=Math.max(0,Number.parseInt(document.querySelector('.days-safe b').textContent,10)||0);if(!state?.date){state={value:initial,date:today}}else{const elapsed=Math.max(0,Math.floor(dayNumber(today)-dayNumber(state.date)));state={value:Math.max(0,Number(state.value)||0)+elapsed+(simulated?1:0),date:today}}document.querySelector('.days-safe b').textContent=state.value;localStorage.setItem(HSE_STORAGE_KEY,JSON.stringify(state))}
function updatePreventionGauge(){const gauge=document.querySelector('.prevention-index'),valueTarget=gauge?.querySelector('b');if(!gauge||!valueTarget)return;const value=Math.max(0,Math.min(100,Number.parseFloat(valueTarget.textContent)||0)),angle=(-180+value*1.8)*Math.PI/180,x=100+Math.cos(angle)*80,y=100+Math.sin(angle)*80,marker=gauge.querySelector('.prevention-hub');valueTarget.textContent=`${Math.round(value)}%`;gauge.querySelector('.prevention-needle').style.display='none';marker.setAttribute('cx',x.toFixed(2));marker.setAttribute('cy',y.toFixed(2));gauge.classList.toggle('low',value<=80);gauge.classList.toggle('medium',value>80&&value<90);gauge.classList.toggle('high',value>=90);gauge.setAttribute('aria-label',`Índice de prevención ${Math.round(value)} por ciento. Tocar para modificar`)}
function writePreventionState(value,entered=true){const safeValue=Math.max(0,Math.min(100,Number.parseFloat(value)||0)),target=document.querySelector('.prevention-index b');if(!target)return;target.textContent=`${safeValue}%`;target.dataset.entered=String(entered);localStorage.setItem(PREVENTION_STORAGE_KEY,JSON.stringify({value:safeValue,entered,updatedAt:new Date().toISOString()}));updatePreventionGauge()}
function syncPreventionState(){let state;try{state=JSON.parse(localStorage.getItem(PREVENTION_STORAGE_KEY)||'null')}catch{state=null}writePreventionState(state?.value??0,Boolean(state?.entered))}
function initializeHsePrevention(){const card=[...document.querySelectorAll('.side-card')].find(item=>item.querySelector('h2')?.textContent.includes('HSE')),header=card?.querySelector('header'),content=card?.querySelector(':scope>div');if(!card||!header||!content)return;card.classList.add('hse-card');const daysView=document.createElement('div'),gauge=document.createElement('div'),toggle=document.createElement('button');daysView.className='hse-days-view';[...content.children].forEach(child=>daysView.append(child));gauge.className='hse-prevention-view';gauge.innerHTML='<span>ÍNDICE DE PREVENCIÓN</span><button type="button" class="prevention-index" data-label="Índice de prevención"><svg viewBox="0 0 200 125" aria-hidden="true"><path class="prevention-track" d="M20 100 A80 80 0 0 1 180 100"/><path class="prevention-range range-red" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><path class="prevention-range range-yellow" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><path class="prevention-range range-green" d="M20 100 A80 80 0 0 1 180 100" pathLength="100"/><line class="prevention-needle" x1="100" y1="100" x2="100" y2="32"/><circle class="prevention-hub" cx="100" cy="100" r="7"/><text x="13" y="117">0</text><text x="145" y="44">80</text><text x="165" y="65">90</text><text x="177" y="117">100</text></svg><b data-entered="false">0%</b></button><div class="prevention-legend"><span><i></i>≤ 80%</span><span><i></i>80–90%</span><span><i></i>≥ 90%</span></div>';toggle.type='button';toggle.className='hse-view-toggle';toggle.innerHTML='<i data-lucide="calendar-days"></i>';toggle.setAttribute('aria-label','Ver días sin accidentes');toggle.title='Ver días sin accidentes';header.append(toggle);content.replaceChildren(daysView,gauge);const setView=view=>{const showIndex=view==='indice';card.classList.toggle('show-prevention',showIndex);toggle.innerHTML=`<i data-lucide="${showIndex?'calendar-days':'gauge'}"></i>`;toggle.setAttribute('aria-label',showIndex?'Ver días sin accidentes':'Ver índice de prevención');toggle.title=showIndex?'Ver días sin accidentes':'Ver índice de prevención';localStorage.setItem('dhl-hse-vista',view);window.lucide?.createIcons()};toggle.addEventListener('click',()=>setView(card.classList.contains('show-prevention')?'dias':'indice'));gauge.querySelector('.prevention-index').addEventListener('click',openEditor);syncPreventionState();setView(localStorage.getItem('dhl-hse-vista')||'indice')}
function qraTargets(){return[...document.querySelectorAll('.radar-score b')]}
function writeQraState(){const targets=qraTargets();localStorage.setItem(QRA_STORAGE_KEY,JSON.stringify({values:targets.map(target=>Math.max(0,Math.min(100,Number.parseFloat(target.textContent)||0))),entered:targets.map(target=>target.dataset.entered==='true'),updatedAt:new Date().toISOString()}));updateQraRadar()}
function syncQraState(){let state;try{state=JSON.parse(localStorage.getItem(QRA_STORAGE_KEY)||'null')}catch{state=null}const targets=qraTargets();if(state?.values?.length===targets.length)targets.forEach((target,index)=>{target.textContent=`${Math.max(0,Math.min(100,Number.parseFloat(state.values[index])||0))}%`;target.dataset.entered=String(Boolean(state.entered?.[index]))});else{targets.forEach(target=>target.textContent=`${Math.max(0,Math.min(100,Number.parseFloat(target.textContent)||0))}%`);writeQraState()}}
function updateQraRadar(){
  const radar=document.querySelector('.qra-radar');if(!radar)return;const values=qraTargets().map(target=>Math.max(0,Math.min(100,Number.parseFloat(target.textContent)||0))),average=Math.round(values.reduce((total,value)=>total+value,0)/values.length),point=(index,radius)=>{const angle=(-90+index*72)*Math.PI/180;return`${50+Math.cos(angle)*radius},${50+Math.sin(angle)*radius}`},polygon=values.map((value,index)=>point(index,38*value/100)).join(' ');
  radar.querySelector('.qra-radar-value').textContent=`${average}%`;radar.querySelector('.qra-data-shape').setAttribute('points',polygon);radar.setAttribute('aria-label',`Promedio QRA 5S ${average} por ciento. Tocar para ver detalle`);
}
function initializeQraRadar(){
  const card=document.querySelector('.qra-card'),content=card?.querySelector(':scope>div'),grid=card?.querySelector('.qra-grid'),header=card?.querySelector('header');if(!card||!content||!grid||!header)return;const points=Array.from({length:5},(_,index)=>{const angle=(-90+index*72)*Math.PI/180;return`${50+Math.cos(angle)*38},${50+Math.sin(angle)*38}`}).join(' '),midPoints=Array.from({length:5},(_,index)=>{const angle=(-90+index*72)*Math.PI/180;return`${50+Math.cos(angle)*19},${50+Math.sin(angle)*19}`}).join(' '),radar=document.createElement('button'),toggleButton=document.createElement('button');radar.type='button';radar.className='qra-radar';radar.innerHTML=`<svg viewBox="0 0 100 100" aria-hidden="true"><polygon class="qra-grid-outer" points="${points}"/><polygon class="qra-grid-inner" points="${midPoints}"/><line x1="50" y1="50" x2="50" y2="12"/><line x1="50" y1="50" x2="86.1" y2="38.3"/><line x1="50" y1="50" x2="72.3" y2="80.7"/><line x1="50" y1="50" x2="27.7" y2="80.7"/><line x1="50" y1="50" x2="13.9" y2="38.3"/><polygon class="qra-data-shape" points="50,50 50,50 50,50 50,50 50,50"/><text x="50" y="7">1S</text><text x="93" y="38">2S</text><text x="77" y="91">3S</text><text x="23" y="91">4S</text><text x="7" y="38">5S</text></svg><span><b class="qra-radar-value">0%</b></span>`;toggleButton.type='button';toggleButton.className='qra-view-toggle';toggleButton.innerHTML=controlIcon('list');toggleButton.setAttribute('aria-label','Ver detalle QRA');toggleButton.title='Ver detalle';header.append(toggleButton);content.prepend(radar);const setDetail=detail=>{card.classList.toggle('qra-detail-mode',detail);toggleButton.innerHTML=controlIcon(detail?'radar':'list');toggleButton.setAttribute('aria-label',detail?'Ver radar QRA':'Ver detalle QRA');toggleButton.title=detail?'Ver radar':'Ver detalle'},toggle=()=>setDetail(!card.classList.contains('qra-detail-mode'));radar.addEventListener('click',()=>setDetail(true));toggleButton.addEventListener('click',toggle);updateQraRadar();
}
function initializeBusinessLineSelector(){
  const configs=[{id:'preparacion',body:document.querySelector('#prepRows')},{id:'despacho',body:document.querySelector('#dispatchRows')}];if(configs.some(config=>!config.body))return;
  let stored=null;try{stored=JSON.parse(localStorage.getItem(BUSINESS_LINES_STORAGE_KEY)||'null')}catch{}const selections={};shifts.forEach(shift=>{selections[shift.id]={};configs.forEach(config=>{const legacy=Array.isArray(stored)?stored:Array.isArray(stored?.[config.id])?stored[config.id]:null,saved=Array.isArray(stored?.[shift.id]?.[config.id])?stored[shift.id][config.id]:legacy||businessLines;selections[shift.id][config.id]=new Set(saved.filter(line=>businessLines.includes(line)));if(!selections[shift.id][config.id].size)selections[shift.id][config.id]=new Set(businessLines)})});
  const activeShift=()=>shiftForCut(document.querySelector('#cutTime').textContent)?.id||'noche';
  const persist=()=>{const payload={};shifts.forEach(shift=>{payload[shift.id]={};configs.forEach(config=>payload[shift.id][config.id]=[...selections[shift.id][config.id]])});localStorage.setItem(BUSINESS_LINES_STORAGE_KEY,JSON.stringify(payload))};
  const closeAll=()=>configs.forEach(config=>{config.menu.hidden=true;config.card.classList.remove('business-menu-open');config.toggle.setAttribute('aria-expanded','false')});
  configs.forEach(config=>{config.card=config.body.closest('.focus-card');const header=config.card.querySelector('h2'),label=config.id==='preparacion'?'Preparación':'Despacho',toggle=document.createElement('button'),menu=document.createElement('div');config.toggle=toggle;config.menu=menu;toggle.type='button';toggle.className='business-lines-toggle';toggle.innerHTML=controlIcon('filter');toggle.title=`Filtrar líneas de ${label}`;toggle.setAttribute('aria-label',`Filtrar líneas de ${label}`);toggle.setAttribute('aria-expanded','false');menu.className='business-lines-menu';menu.hidden=true;menu.innerHTML=`<strong>Líneas de ${label}</strong>${businessLines.map(line=>`<button type="button" data-business-option="${line}"><span>✓</span>${line}</button>`).join('')}`;header.append(toggle);config.card.append(menu);
    config.paint=()=>{const selected=selections[activeShift()][config.id];config.body.querySelectorAll('tr').forEach(row=>row.hidden=!selected.has(row.dataset.businessLine));config.card.dataset.visibleLines=selected.size;menu.querySelectorAll('[data-business-option]').forEach(option=>{const active=selected.has(option.dataset.businessOption);option.classList.toggle('active',active);option.setAttribute('aria-pressed',String(active));option.querySelector('span').textContent=active?'✓':''})};toggle.addEventListener('click',event=>{event.stopPropagation();const opening=menu.hidden;closeAll();if(opening){menu.hidden=false;config.card.classList.add('business-menu-open');toggle.setAttribute('aria-expanded','true')}});menu.addEventListener('click',event=>{event.stopPropagation();const option=event.target.closest('[data-business-option]');if(!option)return;const selected=selections[activeShift()][config.id],line=option.dataset.businessOption;if(selected.has(line)){if(selected.size===1)return;selected.delete(line)}else selected.add(line);config.paint();persist()})});
  refreshBusinessLineFilters=()=>{closeAll();configs.forEach(config=>config.paint())};refreshBusinessLineFilters();persist();
  document.addEventListener('click',closeAll);window.lucide?.createIcons();
}
function migrateSnapshotShape(saved){if(!saved?.values)return saved;const targets=allValues(),newCells=[...document.querySelectorAll('#prepRows tr[data-business-line="WLM RM"] .editable-cell')],insertAt=targets.indexOf(newCells[0]);if(newCells.length&&insertAt>=0&&saved.values.length===targets.length-newCells.length){saved.values=[...saved.values];saved.entered=[...(saved.entered||saved.values.map(()=>false))];saved.values.splice(insertAt,0,...newCells.map(()=>'0'));saved.entered.splice(insertAt,0,...newCells.map(()=>false))}return saved}
function getSnapshot(){return{schemaVersion:3,values:allValues().map(element=>element.textContent),entered:allValues().map(element=>element.dataset.entered==='true'),notes:document.querySelector('textarea')?.value||'',cut:document.querySelector('#cutTime').textContent,crew:structuredClone(crew),crewEntered:structuredClone(crewEntered),transferBalance:structuredClone(transferBalance)}}
function emptyDailyRecord(){return{date:todayKey(),sessions:{},drafts:{},updatedAt:null}}
function readDailyRecord(){try{const parsed=JSON.parse(localStorage.getItem(JSON_STORAGE_KEY)||'null');if(parsed?.date===todayKey()){const record={...parsed,sessions:parsed.sessions||{},drafts:parsed.drafts||{}};Object.values(record.sessions).forEach(migrateSnapshotShape);Object.values(record.drafts).forEach(migrateSnapshotShape);return record}localStorage.removeItem(JSON_STORAGE_KEY);return emptyDailyRecord()}catch{localStorage.removeItem(JSON_STORAGE_KEY);return emptyDailyRecord()}}
function writeDailyRecord(){localStorage.setItem(JSON_STORAGE_KEY,JSON.stringify(dailyRecord))}
function markDirty(){dirty=true;document.body.classList.add('has-unsaved');const current=document.querySelector(`.cut-chip[data-cut="${document.querySelector('#cutTime').textContent}"]`);current?.classList.remove('complete');current?.classList.add('incomplete');document.querySelector('#lastSaved').textContent='Cambios sin guardar'}
function validateCurrentMeeting(){
  const missing=[],sectionNames={foco:'Foco',productividad:'Productividad',horas:'Horas'};
  for(const [indicator,label] of Object.entries(sectionNames)){
    document.querySelectorAll(`.data-card[data-indicator="${indicator}"]`).forEach(card=>{
      const targets=[...card.querySelectorAll('.stat b,.editable-cell')].filter(target=>!target.closest('tr')?.hidden);
      if(!targets.some(target=>target.dataset.entered==='true'))missing.push(`${label} · ${areaNames[card.dataset.area]||card.dataset.area}`);
    });
  }
  Object.entries(crewEntered).forEach(([area,roles])=>{if(!roles.operativo&&!roles.grua)missing.push(`Dotación · ${areaNames[area]}`)});
  return{valid:missing.length===0,missing};
}
function paintMeetingStates(){document.querySelectorAll('.cut-chip').forEach(button=>{const session=dailyRecord?.sessions?.[button.dataset.cut],hasDraft=Boolean(dailyRecord?.drafts?.[button.dataset.cut]),complete=Boolean(session?.validation?.valid&&!hasDraft),warning=Boolean(session&&!session?.validation?.valid&&!hasDraft);button.classList.toggle('complete',complete);button.classList.toggle('warning',warning);button.classList.toggle('incomplete',!complete&&!warning)});document.querySelectorAll('.shift-group').forEach(group=>{const buttons=[...group.querySelectorAll('.cut-chip')],allComplete=buttons.every(button=>button.classList.contains('complete')),hasWarning=buttons.some(button=>button.classList.contains('warning'));group.classList.toggle('complete-shift',allComplete);group.classList.toggle('warning-shift',!allComplete&&hasWarning)})}
function saveCurrentMeeting(){const validation=validateCurrentMeeting(),snapshot={...getSnapshot(),completed:validation.valid,validation,updatedAt:new Date().toISOString()};dailyRecord.sessions[snapshot.cut]=snapshot;delete dailyRecord.drafts[snapshot.cut];dailyRecord.updatedAt=snapshot.updatedAt;writeDailyRecord();dirty=false;document.body.classList.remove('has-unsaved');paintMeetingStates();document.querySelector('#lastSaved').textContent=validation.valid?`Reunión ${snapshot.cut} completa · guardada`:`Reunión ${snapshot.cut} guardada incompleta · faltan ${validation.missing.length} secciones`}
function applySnapshot(saved){if(!saved)return;if(saved.values?.length){const targets=allValues(),limit=Math.min(saved.values.length,targets.length);saved.values.slice(0,limit).forEach((value,index)=>{const target=targets[index];target.textContent=target.classList.contains('prep-advance')?String(value).replace('%',''):value;const wasEntered=saved.entered?.[index]??Number.parseFloat(String(value).replace(',','.'))!==0;target.dataset.entered=String(Boolean(wasEntered))})}const notes=document.querySelector('textarea');if(saved.notes!==undefined&&notes)notes.value=saved.notes;if(saved.cut){document.querySelector('#cutTime').textContent=saved.cut;document.querySelectorAll('.cut-chip').forEach(button=>button.classList.toggle('active',button.dataset.cut===saved.cut))}if(saved.crew?.recepcion){for(const area of Object.keys(crew))crew[area]={...crew[area],...saved.crew[area]}}if(saved.crewEntered)crewEntered=structuredClone(saved.crewEntered);else for(const area of Object.keys(crewEntered)){crewEntered[area].operativo=crew[area].operativo!==0;crewEntered[area].grua=crew[area].grua!==0}}
function blankSnapshot(cut){const blank=structuredClone(initialSnapshot);blank.cut=cut;blank.notes='';blank.values=blank.values.map(()=>'0');blank.entered=blank.values.map(()=>false);blank.transferBalance=emptyTransferBalance();Object.keys(blank.crew).forEach(area=>{blank.crew[area].operativo=0;blank.crew[area].grua=0;blank.crewEntered[area].operativo=false;blank.crewEntered[area].grua=false});return blank}
function shiftForCut(cut){return shifts.find(shift=>shift.cuts.includes(cut))}
function inheritedSnapshot(cut){const shift=shiftForCut(cut),index=shift.cuts.indexOf(cut);for(let position=index-1;position>=0;position--){const previousCut=shift.cuts[position],snapshot=dailyRecord.drafts[previousCut]||dailyRecord.sessions[previousCut];if(snapshot)return{snapshot:structuredClone(snapshot),source:previousCut}}return null}
function storeCurrentDraft(){if(!dirty)return;const snapshot={...getSnapshot(),completed:false,updatedAt:new Date().toISOString()};dailyRecord.drafts[snapshot.cut]=snapshot;dailyRecord.updatedAt=snapshot.updatedAt;writeDailyRecord();paintMeetingStates()}
function legacyLoadMeeting(cut){const saved=dailyRecord.sessions[cut],draft=dailyRecord.drafts[cut],inherited=!saved&&!draft?inheritedSnapshot(cut):null,source=draft||saved||inherited?.snapshot||blankSnapshot(cut);applySnapshot({...structuredClone(source),cut});document.querySelector('#cutTime').textContent=cut;updateInlineCounts();dirty=Boolean(draft);document.body.classList.toggle('has-unsaved',dirty);document.querySelector('#lastSaved').textContent=draft?`Borrador ${cut} · sin guardar`:saved?`Reunión ${cut} completada`:inherited?`Base heredada desde ${inherited.source}`:'Inicio de turno · reunión pendiente'}
function resetForNewDay(simulated=false){syncSafetyCounter(simulated);activeDate=todayKey();dailyRecord=emptyDailyRecord();writeDailyRecord();paintMeetingStates();loadMeeting(cuts[0]);closeCalculators();closeClearPanel();document.querySelector('#lastSaved').textContent=simulated?'Cambio de día simulado · tablero limpio':'Nuevo día · tablero limpio'}
function loadMeeting(cut){const saved=dailyRecord.sessions[cut],draft=dailyRecord.drafts[cut],inherited=!saved&&!draft?inheritedSnapshot(cut):null,source=draft||saved||inherited?.snapshot||blankSnapshot(cut);applySnapshot({...structuredClone(source),cut});transferBalance=structuredClone(source.transferBalance||emptyTransferBalance());document.querySelector('#cutTime').textContent=cut;updateInlineCounts();dirty=Boolean(draft);document.body.classList.toggle('has-unsaved',dirty);document.querySelector('#lastSaved').textContent=draft?`Borrador ${cut} · sin guardar`:saved?`Reunión ${cut} completada`:inherited?`Base heredada desde ${inherited.source}`:'Inicio de turno · reunión pendiente'}
function checkDayChange(){if(todayKey()!==activeDate)resetForNewDay()}
function paintSystemDate(){document.querySelector('#systemDate').textContent=new Intl.DateTimeFormat('es-CL',{timeZone:'America/Santiago',weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date()).replace(/\./g,'')}
function editableTarget(element){return element.matches('.stat,.radar-score,.days-safe,.workforce-numbers,.prevention-index')?element.querySelector('b,strong'):element}
function editorLabel(element){return element.dataset.label||element.closest('tr')?.firstElementChild.textContent||'Valor'}
function positionCalculator(card,target,index){const rect=target.getBoundingClientRect(),width=card.offsetWidth,height=card.offsetHeight;let left=rect.right+10,top=rect.top;if(left+width>window.innerWidth-10)left=rect.left-width-10;if(left<10)left=10;if(top+height>window.innerHeight-10)top=window.innerHeight-height-10;top=Math.max(10,top+(index%3)*14);card.style.left=`${left}px`;card.style.top=`${top}px`}
function makeDraggable(card,handle){let drag=null;handle.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;const rect=card.getBoundingClientRect();drag={dx:event.clientX-rect.left,dy:event.clientY-rect.top};handle.setPointerCapture(event.pointerId)});handle.addEventListener('pointermove',event=>{if(!drag)return;card.style.left=`${Math.max(0,Math.min(window.innerWidth-card.offsetWidth,event.clientX-drag.dx))}px`;card.style.top=`${Math.max(0,Math.min(window.innerHeight-card.offsetHeight,event.clientY-drag.dy))}px`});handle.addEventListener('pointerup',()=>drag=null);handle.addEventListener('pointercancel',()=>drag=null)}
function openEditor(event){
  const source=event.currentTarget,target=editableTarget(source);if(target.dataset.editorId){const openCard=document.querySelector(`#${target.dataset.editorId}`);delete target.dataset.editorId;openCard?.remove();return}
  const indicator=source.closest('.data-card')?.dataset.indicator,qraScore=source.matches('.radar-score'),preventionScore=source.matches('.prevention-index'),allowNegative=indicator==='productividad',id=`calculator-${crypto.randomUUID?.()||Date.now()}-${Math.floor(Math.random()*999)}`,suffix=indicator==='horas'||qraScore||preventionScore||target.textContent.includes('%')?'%':'';let value=target.textContent.replace(/[^0-9.,-]/g,'').replace(',','.')||'0';if(!allowNegative&&Number(value)<0)value=String(Math.abs(Number(value)));
  const keys=['1','2','3','4','5','6','7','8','9',...(allowNegative?['±']:[]),'0',',','⌫'];const card=document.createElement('section');card.className='contextual-calculator';card.id=id;card.innerHTML=`<header><span><i data-lucide="calculator"></i><b>${editorLabel(source)}</b></span><button class="calculator-close" aria-label="Cerrar">×</button></header><div class="calculator-display">${value}${suffix}</div><div class="calculator-keys">${keys.map(key=>`<button data-key="${key}"${key==='⌫'?' class="calculator-delete"':''}>${key==='⌫'?'<i data-lucide="delete"></i><span>Borrar</span>':key}</button>`).join('')}</div><button class="calculator-save"><i data-lucide="check-circle"></i><span>Aplicar valor</span></button>`;
  document.body.appendChild(card);target.dataset.editorId=id;const display=card.querySelector('.calculator-display'),paint=()=>display.textContent=`${value}${suffix}`,close=()=>{delete target.dataset.editorId;card.remove()};
  card.querySelector('.calculator-close').addEventListener('click',close);card.querySelectorAll('.calculator-keys button').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.key;if(key==='⌫')value=value.length>1?value.slice(0,-1):'0';else if(key==='±')value=value.startsWith('-')?value.slice(1):`-${value}`;else if(key===','){if(!value.includes('.'))value+='.'}else value=value==='0'?key:`${value}${key}`;paint()}));
  card.querySelector('.calculator-save').addEventListener('click',()=>{if(!allowNegative&&Number(value)<0)value='0';if((indicator==='horas'||qraScore||preventionScore)&&Number(value)>100)value='100';target.textContent=`${value}${suffix}`;target.dataset.entered='true';if(target.closest('.days-safe')){writeSafetyCounter(value);close();return}if(target.closest('.radar-score')){writeQraState();close();return}if(target.closest('.prevention-index')){writePreventionState(value,true);close();return}const workforceField=target.closest('.workforce-numbers'),roleRow=target.closest('.workforce-role'),areaCard=target.closest('.dotacion');if(workforceField&&roleRow&&areaCard){const field=workforceField.dataset.field;crew[areaCard.dataset.area][field]=Math.max(0,Number(value)||0);if(field===roleRow.dataset.role)crewEntered[areaCard.dataset.area][roleRow.dataset.role]=true;target.textContent=crew[areaCard.dataset.area][field]}markDirty();close()});makeDraggable(card,card.querySelector('header'));positionCalculator(card,target,document.querySelectorAll('.contextual-calculator').length-1);window.lucide?.createIcons({attrs:{'stroke-width':2}});
}
document.querySelectorAll('.stat:not(.dotacion .stat),.editable-cell,.radar-score,.days-safe').forEach(element=>element.addEventListener('click',openEditor));
document.querySelector('textarea')?.addEventListener('input',markDirty);
document.querySelector('#saveMeeting').addEventListener('click',saveCurrentMeeting);
function simulateMeetingData(){
  transferBalance=emptyTransferBalance();
  document.querySelectorAll('.data-card[data-indicator]').forEach(card=>{
    const indicator=card.dataset.indicator;if(indicator==='dotacion')return;
    card.querySelectorAll('.stat b,.editable-cell').forEach((target,index)=>{const value=indicator==='productividad'?Math.floor(Math.random()*31)-10:indicator==='horas'?Math.floor(Math.random()*101):target.classList.contains('prep-advance')?Math.floor(Math.random()*151)+1:Math.floor(Math.random()*801)+1;target.textContent=indicator==='horas'?`${value}%`:value;target.dataset.entered='true'});
  });
  const basePlans={recepcion:{operativo:92,grua:22},preparacion:{operativo:45,grua:12},despacho:{operativo:33,grua:10}};
  Object.keys(crew).forEach(area=>{const base=basePlans[area];crew[area].planOperativo=Math.max(1,base.operativo+Math.floor(Math.random()*7)-3);crew[area].planGrua=Math.max(1,base.grua+Math.floor(Math.random()*5)-2);crew[area].operativo=Math.max(1,Math.floor(crew[area].planOperativo*(.72+Math.random()*.25)));crew[area].grua=Math.max(1,Math.floor(crew[area].planGrua*(.72+Math.random()*.25)));crewEntered[area].operativo=true;crewEntered[area].grua=true});
  updateInlineCounts();qraTargets().forEach(target=>{target.textContent=Math.floor(Math.random()*31)+70;target.dataset.entered='true'});writeQraState();closeCalculators();markDirty();document.querySelector('#lastSaved').textContent='Datos de prueba cargados · sin guardar';
}
document.querySelector('#simulateData').addEventListener('click',simulateMeetingData);
document.querySelector('#simulateNextDay').addEventListener('click',()=>resetForNewDay(true));
document.querySelector('#resetSafeDays').addEventListener('click',()=>{writeSafetyCounter(0);closeCalculators();document.querySelector('#lastSaved').textContent='Contador HSE reiniciado en 0'});
document.querySelectorAll('.cut-chip').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.cut===document.querySelector('#cutTime').textContent)return;storeCurrentDraft();document.querySelectorAll('.cut-chip').forEach(item=>item.classList.remove('active'));button.classList.add('active');loadMeeting(button.dataset.cut)}));
function initializeAreaMetadata(){document.querySelectorAll('.process-label').forEach((label,index)=>{const area=['recepcion','preparacion','despacho'][index];let card=label.nextElementSibling;['foco','productividad','horas','dotacion'].forEach(indicator=>{if(card?.classList.contains('data-card')){card.dataset.area=area;card.dataset.indicator=indicator;card=card.nextElementSibling}})})}
function closeCalculators(){document.querySelectorAll('.contextual-calculator').forEach(card=>card.remove());document.querySelectorAll('[data-editor-id]').forEach(target=>delete target.dataset.editorId)}
function closeClearPanel(){const panel=document.querySelector('#clearAreas');panel.classList.remove('open','choose-section');panel.setAttribute('aria-hidden','true');panel.style.removeProperty('position');panel.style.removeProperty('left');panel.style.removeProperty('top');panel.style.removeProperty('right');selectedClearArea=null}
function bindDraggableClearPanel(){
  const panel=document.querySelector('#clearAreas');let drag=null;
  const bounds=()=>({maxLeft:Math.max(8,window.innerWidth-panel.offsetWidth-8),maxTop:Math.max(8,window.innerHeight-panel.offsetHeight-8)});panel.addEventListener('pointerdown',event=>{const handle=event.target.closest('.clear-step>b');if(!handle)return;const rect=panel.getBoundingClientRect(),limits=bounds(),left=Math.max(8,Math.min(limits.maxLeft,rect.left)),top=Math.max(8,Math.min(limits.maxTop,rect.top));drag={dx:event.clientX-left,dy:event.clientY-top,pointerId:event.pointerId,handle};panel.style.position='fixed';panel.style.left=`${left}px`;panel.style.top=`${top}px`;panel.style.right='auto';handle.setPointerCapture(event.pointerId);event.preventDefault()});
  panel.addEventListener('pointermove',event=>{if(!drag)return;const limits=bounds(),left=Math.max(8,Math.min(limits.maxLeft,event.clientX-drag.dx)),top=Math.max(8,Math.min(limits.maxTop,event.clientY-drag.dy));panel.style.left=`${left}px`;panel.style.top=`${top}px`});
  const stop=()=>{if(drag?.handle?.hasPointerCapture(drag.pointerId))drag.handle.releasePointerCapture(drag.pointerId);drag=null};panel.addEventListener('pointerup',stop);panel.addEventListener('pointercancel',stop);
}
function clearSection(area,indicator){
  const card=document.querySelector(`.data-card[data-area="${area}"][data-indicator="${indicator}"]`);if(!card)return;
  if(indicator==='foco')card.querySelectorAll('.stat b,.editable-cell').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  if(indicator==='productividad'||indicator==='horas')card.querySelectorAll('.stat b').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  if(indicator==='dotacion'){settleTransfers();crew[area].operativo=0;crew[area].grua=0;crew[area].planOperativo=0;crew[area].planGrua=0;crewEntered[area].operativo=false;crewEntered[area].grua=false;updateInlineCounts()}
  closeCalculators();closeClearPanel();markDirty();const sectionNames={foco:'Foco',productividad:'Productividad',horas:'Horas',dotacion:'Dotación'};document.querySelector('#lastSaved').textContent=`${areaNames[area]} · ${sectionNames[indicator]} limpiado · sin guardar`;
}
function clearEverything(){
  transferBalance=emptyTransferBalance();
  document.querySelectorAll('.data-card[data-indicator="foco"] .stat b,.data-card[data-indicator="foco"] .editable-cell').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  document.querySelectorAll('.data-card[data-indicator="productividad"] .stat b,.data-card[data-indicator="horas"] .stat b').forEach(target=>{target.textContent='0';target.dataset.entered='false'});
  Object.keys(crew).forEach(area=>{crew[area].operativo=0;crew[area].grua=0;crew[area].planOperativo=0;crew[area].planGrua=0;crewEntered[area].operativo=false;crewEntered[area].grua=false});updateInlineCounts();closeCalculators();closeClearPanel();markDirty();document.querySelector('#lastSaved').textContent='Horario actual limpiado · sin guardar';
}
function summarySnapshots(){
  const currentCut=document.querySelector('#cutTime').textContent,currentHasData=allValues().some(target=>target.dataset.entered==='true')||Object.values(crewEntered).some(area=>area.operativo||area.grua);
  return cuts.map(cut=>{let snapshot=dailyRecord.drafts[cut]||dailyRecord.sessions[cut]||null;if(cut===currentCut&&(dirty||currentHasData))snapshot={...getSnapshot(),validation:validateCurrentMeeting()};return{cut,snapshot}});
}
function summaryMetrics(snapshot){
  if(!snapshot)return null;const areaKeys=['recepcion','preparacion','despacho'],grouped={foco:{},productividad:{},horas:{}},targets=allValues(),valid=values=>values.filter(value=>value!==null),sum=values=>valid(values).reduce((total,value)=>total+value,0),average=values=>valid(values).length?sum(values)/valid(values).length:null,percent=(done,total)=>done!==null&&total?Math.max(0,Math.min(100,done/total*100)):null;
  areaKeys.forEach(area=>Object.keys(grouped).forEach(indicator=>grouped[indicator][area]=[]));
  (snapshot.values||[]).forEach((value,index)=>{const card=targets[index]?.closest('.data-card'),indicator=card?.dataset.indicator,area=card?.dataset.area;if(grouped[indicator]?.[area])grouped[indicator][area].push(snapshot.entered?.[index]===false?null:Number.parseFloat(String(value).replace(',','.'))||0)});
  const reception=grouped.foco.recepcion,preparation=grouped.foco.preparacion,dispatching=grouped.foco.despacho,prepAssigned=preparation.filter((_,index)=>index%3===1),prepAdvance=preparation.filter((_,index)=>index%3===2),dispatchAssigned=dispatching.filter((_,index)=>index%4===0),dispatched=dispatching.filter((_,index)=>index%4===3),foco={recepcion:percent(reception[1]===null&&reception[2]===null?null:(reception[1]||0)+(reception[2]||0),reception[0]),preparacion:percent(valid(prepAdvance).length?sum(prepAdvance):null,sum(prepAssigned)),despacho:percent(valid(dispatched).length?sum(dispatched):null,sum(dispatchAssigned))},productividad={},horas={},dotacion={};
  areaKeys.forEach(area=>{productividad[area]=average(grouped.productividad[area]);const hourAverage=average(grouped.horas[area]);horas[area]=hourAverage===null?null:Math.max(0,Math.min(100,hourAverage));const staff=snapshot.crew?.[area]||{},staffEntered=snapshot.crewEntered?.[area],balance=snapshot.transferBalance?.[area]||{},hasAttendance=staffEntered?staffEntered.operativo||staffEntered.grua:true,attended=(Number(staff.operativo)||0)+(Number(staff.grua)||0)-(Number(balance.operativo)||0)-(Number(balance.grua)||0),planned=(Number(staff.planOperativo)||0)+(Number(staff.planGrua)||0);dotacion[area]=hasAttendance?percent(attended,planned):null});
  return{foco,productividad,horas,dotacion};
}
function summaryLineChart(chart,records){
  const areaKeys=['recepcion','preparacion','despacho'],colors={recepcion:'#43bff2',preparacion:'#ffd23f',despacho:'#ef535b'},labels={recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'},width=900,height=220,left=48,right=880,top=18,bottom=178,x=index=>left+(right-left)*index/(cuts.length-1),y=value=>top+(chart.max-value)/(chart.max-chart.min)*(bottom-top),ticks=Array.from({length:5},(_,index)=>chart.max-(chart.max-chart.min)*index/4);
  const grid=ticks.map(value=>`<line x1="${left}" y1="${y(value)}" x2="${right}" y2="${y(value)}"/><text x="${left-8}" y="${y(value)+4}" text-anchor="end">${Math.round(value)}${chart.unit}</text>`).join(''),bands=['noche','manana','tarde'].map((shift,index)=>`<rect class="shift-band ${shift}" x="${Math.max(0,x(index*3)-42)}" y="${top}" width="${index===2?right-(x(6)-42):x(index*3+3)-x(index*3)}" height="${bottom-top}"/>`).join('');
  const series=areaKeys.map(area=>{const values=records.map(record=>record.metrics?.[chart.key]?.[area]??null),segments=values.slice(0,-1).map((value,index)=>value!==null&&values[index+1]!==null?`<line class="series-line" x1="${x(index)}" y1="${y(value)}" x2="${x(index+1)}" y2="${y(values[index+1])}"/>`:'').join(''),points=values.map((value,index)=>value===null?'':`<g class="series-point"><circle cx="${x(index)}" cy="${y(value)}" r="4"><title>${labels[area]} · ${records[index].cut}: ${value.toFixed(1)}${chart.unit}</title></circle><text x="${x(index)}" y="${Math.max(12,y(value)-8)}" text-anchor="middle">${Math.round(value)}${chart.unit}</text></g>`).join('');return`<g class="area-series ${area}" style="--series:${colors[area]}">${segments}${points}</g>`}).join('');
  const hours=records.map((record,index)=>`<text class="axis-hour" x="${x(index)}" y="205" text-anchor="middle">${record.cut}</text>`).join('');
  return`<article class="summary-chart line-chart"><header><div><i data-lucide="${chart.icon}"></i><span><h3>${chart.title}</h3><small>${chart.description}</small></span></div><div class="area-legend">${areaKeys.map(area=>`<span><i style="background:${colors[area]}"></i>${labels[area]}</span>`).join('')}</div></header><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none" aria-label="${chart.title}">${bands}<g class="chart-grid">${grid}</g>${series}${hours}</svg></article>`;
}
function summaryAreaChart(area,records,metrics){
  const areaInfo={recepcion:{label:'Recepción',icon:'package-open'},preparacion:{label:'Preparación',icon:'boxes'},despacho:{label:'Despacho',icon:'truck'}}[area],shiftColors={noche:'#43bff2',manana:'#ffd23f',tarde:'#ef535b'},width=900,height=108,left=45,right=880,top=12,bottom=72,x=index=>left+(right-left)*index/(cuts.length-1);
  const metricCharts=metrics.map(metric=>{const y=value=>top+(metric.max-value)/(metric.max-metric.min)*(bottom-top),values=records.map(record=>record.metrics?.[metric.key]?.[area]??null),gridValues=metric.min<0?[metric.max,0,metric.min]:[metric.max,metric.max/2,metric.min],grid=gridValues.map(value=>`<line x1="${left}" y1="${y(value)}" x2="${right}" y2="${y(value)}"/><text x="${left-7}" y="${y(value)+3}" text-anchor="end">${Math.round(value)}${metric.unit}</text>`).join(''),segments=values.slice(0,-1).map((value,index)=>{if(value===null||values[index+1]===null)return'';const currentShift=shiftForCut(records[index].cut)?.id,nextShift=shiftForCut(records[index+1].cut)?.id;if(currentShift!==nextShift)return'';return`<line class="shift-series ${currentShift}" x1="${x(index)}" y1="${y(value)}" x2="${x(index+1)}" y2="${y(values[index+1])}"/>`}).join(''),points=values.map((value,index)=>{if(value===null)return'';const shift=shiftForCut(records[index].cut)?.id||'noche';return`<g class="shift-point ${shift}"><circle cx="${x(index)}" cy="${y(value)}" r="4"><title>${areaInfo.label} · ${metric.title} · ${records[index].cut}: ${value.toFixed(1)}${metric.unit}</title></circle><text x="${x(index)}" y="${Math.max(9,y(value)-7)}" text-anchor="middle">${Math.round(value)}${metric.unit}</text></g>`}).join(''),hours=records.map((record,index)=>`<text class="axis-hour" x="${x(index)}" y="99" text-anchor="middle">${record.cut}</text>`).join('');return`<section class="area-metric-chart"><div><i data-lucide="${metric.icon}"></i><span><b>${metric.title}</b><small>${metric.description}</small></span></div><svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="none"><g class="chart-grid">${grid}</g>${segments}${points}${hours}</svg></section>`}).join('');
  return`<article class="area-summary-card ${area}"><header><i data-lucide="${areaInfo.icon}"></i><h3>${areaInfo.label}</h3></header><div class="area-metrics">${metricCharts}</div></article>`;
}
function legacyAreaDashboardHtml(area,records){
  const info={recepcion:{label:'Recepción',icon:'package-open',formula:'Rechazados + en auditoría respecto de agendados'},preparacion:{label:'Preparación',icon:'boxes',formula:'Avance procesado respecto de líneas asignadas'},despacho:{label:'Despacho',icon:'truck',formula:'Despachado respecto del total asignado'}}[area],values=key=>records.map(record=>record.metrics?.[key]?.[area]??null),advance=values('foco'),productivity=values('productividad'),hours=values('horas'),attendance=values('dotacion'),latest=list=>[...list].reverse().find(value=>value!==null)??0,shift=index=>shiftForCut(records[index].cut)?.id||'noche',format=value=>value===null?'—':`${Math.round(value)}%`,sessionTiles=(list,type)=>list.map((value,index)=>`<div class="dashboard-session ${shift(index)} ${type}" style="--level:${Math.max(0,Math.min(100,value??0))}"><small>${records[index].cut}</small><b>${format(value)}</b><i></i></div>`).join(''),maxProductivity=Math.max(10,...productivity.filter(value=>value!==null).map(value=>Math.abs(value)));
  const productivityBars=productivity.map((value,index)=>`<div class="productivity-column ${shift(index)} ${value<0?'negative':'positive'}"><b>${value===null?'—':value.toFixed(1)}</b><div class="productivity-track"><i style="height:${value===null?0:Math.max(3,Math.abs(value)/maxProductivity*48)}%"></i></div><small>${records[index].cut}</small></div>`).join(''),hoursHeat=hours.map((value,index)=>`<div class="heat-cell ${shift(index)}" style="--heat:${(value??0)/100}"><small>${records[index].cut}</small><b>${format(value)}</b><span>${value===null?'Sin datos':value>=80?'Óptimo':value>=50?'Medio':'Bajo'}</span></div>`).join(''),attendanceBars=attendance.map((value,index)=>`<div class="attendance-column ${shift(index)}"><b>${format(value)}</b><div><i style="height:${Math.max(0,Math.min(100,value??0))}%"></i></div><small>${records[index].cut}</small></div>`).join('');
  return`<section class="area-dashboard"><article class="dashboard-panel advance-panel"><header><span><i data-lucide="target"></i><b>Avance operacional</b></span><small>${info.formula}</small></header><div class="advance-body"><div class="progress-ring" style="--progress:${latest(advance)}"><div><b>${Math.round(latest(advance))}%</b><small>último registro</small></div></div><div class="session-strip">${sessionTiles(advance,'advance')}</div></div></article><article class="dashboard-panel productivity-panel"><header><span><i data-lucide="gauge"></i><b>Productividad</b></span><small>Variación promedio por sesión</small></header><div class="productivity-bars">${productivityBars}</div></article><article class="dashboard-panel hours-panel"><header><span><i data-lucide="clock-3"></i><b>Horas directas</b></span><small>Intensidad porcentual · máximo 100%</small></header><div class="hours-heatmap">${hoursHeat}</div></article><article class="dashboard-panel attendance-panel"><header><span><i data-lucide="users-round"></i><b>Asistencia</b></span><small>Presentes respecto de dotación total</small></header><div class="attendance-bars">${attendanceBars}</div></article></section>`;
}
function areaDashboardHtml(area,records){
  const values=key=>records.map(record=>record.metrics?.[key]?.[area]??null),productivity=values('productividad'),hours=values('horas'),attendance=values('dotacion'),shift=index=>shiftForCut(records[index].cut)?.id||'noche',format=value=>value===null?'—':`${Math.round(value)}%`,maxProductivity=Math.max(10,...productivity.filter(value=>value!==null).map(value=>Math.abs(value)));
  const shiftNames={noche:'Turno noche',manana:'Turno mañana',tarde:'Turno tarde'},shiftOrder=['noche','manana','tarde'],cubeValues=shiftOrder.map(shiftId=>{const meetings=records.map((record,index)=>({shiftId:shift(index),productivity:productivity[index],hours:hours[index],attendance:attendance[index]})).filter(meeting=>meeting.shiftId===shiftId&&meeting.productivity!==null&&meeting.hours!==null&&meeting.attendance!==null),results=meetings.map(meeting=>Math.max(0,100+meeting.productivity)/100*(meeting.hours/100)*(meeting.attendance/100)*100),average=results.length?results.reduce((total,value)=>total+value,0)/results.length:null;return{shiftId,average,count:results.length}}),cubeCards=cubeValues.map(item=>`<div class="shift-cube-card ${item.shiftId}"><div class="shift-cube" style="--cube-level:${Math.max(0,Math.min(100,item.average??0))}%" aria-label="${shiftNames[item.shiftId]}; desempeño ${format(item.average)}"><span class="cube-face cube-front"><b>${format(item.average)}</b></span><span class="cube-face cube-top"></span><span class="cube-face cube-side"></span></div><strong>${shiftNames[item.shiftId]}</strong><small>${item.count?`${item.count} reunión${item.count===1?'':'es'} promediada${item.count===1?'':'s'}`:'Sin reuniones completas'}</small></div>`).join('');
  const productivityBars=productivity.map((value,index)=>`<div class="productivity-column ${shift(index)} ${value<0?'negative':'positive'}"><b>${value===null?'—':value.toFixed(1)}</b><div class="productivity-track"><i style="height:${value===null?0:Math.max(3,Math.abs(value)/maxProductivity*48)}%"></i></div><small>${records[index].cut}</small></div>`).join(''),hoursHeat=hours.map((value,index)=>`<div class="heat-cell ${shift(index)}" style="--heat:${(value??0)/100}"><small>${records[index].cut}</small><b>${format(value)}</b><span>${value===null?'Sin datos':value>=80?'Óptimo':value>=50?'Medio':'Bajo'}</span></div>`).join(''),attendanceBars=attendance.map((value,index)=>`<div class="attendance-column ${shift(index)}"><b>${format(value)}</b><div><i style="height:${Math.max(0,Math.min(100,value??0))}%"></i></div><small>${records[index].cut}</small></div>`).join('');
  return`<section class="area-dashboard"><article class="dashboard-panel performance-panel"><header><span><i data-lucide="box"></i><b>Desempeño por turno</b></span><small>(100% + variación) × horas directas × asistencia</small></header><div class="shift-cubes">${cubeCards}</div></article><article class="dashboard-panel productivity-panel"><header><span><i data-lucide="gauge"></i><b>Productividad</b></span><small>Variación promedio por sesión</small></header><div class="productivity-bars">${productivityBars}</div></article><article class="dashboard-panel hours-panel"><header><span><i data-lucide="clock-3"></i><b>Horas directas</b></span><small>Intensidad porcentual · máximo 100%</small></header><div class="hours-heatmap">${hoursHeat}</div></article><article class="dashboard-panel attendance-panel"><header><span><i data-lucide="users-round"></i><b>Asistencia</b></span><small>Presentes respecto de dotación total</small></header><div class="attendance-bars">${attendanceBars}</div></article></section>`;
}
function renderSummary(){
  const view=document.querySelector('#summaryView'),records=summarySnapshots().map(item=>({...item,metrics:summaryMetrics(item.snapshot)})),charts=[{key:'foco',title:'Avance operacional',description:'Recepción: rechazados + auditoría / agendados · Preparación: avance / asignado · Despacho: despachado / asignado',unit:'%',min:0,max:100,icon:'target'},{key:'productividad',title:'Productividad por área',description:'Promedio de variación entre operativo y grúa',unit:'',min:-100,max:100,icon:'gauge'},{key:'horas',title:'Horas directas por área',description:'Porcentaje promedio de operativo y grúa · máximo 100%',unit:'%',min:0,max:100,icon:'clock-3'},{key:'dotacion',title:'Asistencia de dotación',description:'Asistencia real respecto de la dotación total',unit:'%',min:0,max:100,icon:'users-round'}];
  const available=records.filter(record=>record.snapshot),complete=available.filter(record=>record.snapshot.validation?.valid||record.snapshot.completed).length;
  view.querySelector('.summary-content').innerHTML=`<div class="summary-overview"><span><b>${available.length}</b> sesiones registradas</span><span><b>${complete}</b> completas</span><div class="summary-legend"><i class="noche"></i>Noche<i class="manana"></i>Mañana<i class="tarde"></i>Tarde</div></div><nav class="area-tabs">${Object.entries({recepcion:'Recepción',preparacion:'Preparación',despacho:'Despacho'}).map(([area,label])=>`<button class="${area===activeSummaryArea?'active':''}" data-summary-area="${area}">${label}</button>`).join('')}</nav>${areaDashboardHtml(activeSummaryArea,records)}`;
  view.querySelectorAll('[data-summary-area]').forEach(button=>button.addEventListener('click',()=>{activeSummaryArea=button.dataset.summaryArea;renderSummary()}));
  window.lucide?.createIcons();
}
function initializeSummary(){
  const view=document.createElement('main');view.id='summaryView';view.className='summary-view';view.innerHTML='<header class="summary-header"><div><i data-lucide="chart-no-axes-combined"></i><span><small>AVANCE ACUMULADO</small><h2>Resumen del día</h2></span></div><button id="closeSummary" type="button"><i data-lucide="arrow-left"></i>Volver al tablero</button></header><section class="summary-content"></section>';document.querySelector('.board').insertAdjacentElement('afterend',view);
  const closeButton=view.querySelector('#closeSummary');document.querySelector('.logo-box').insertAdjacentElement('afterend',closeButton);const open=()=>{closeCalculators();closeClearPanel();renderSummary();document.body.classList.add('summary-open');history.replaceState(null,'','#resumen')},close=()=>{document.body.classList.remove('summary-open');history.replaceState(null,'',location.pathname+location.search)},trigger=document.querySelector('.summary-access-card');trigger.innerHTML='<header><h2><i data-lucide="badge-check"></i>OMS</h2></header><button id="openSummary" type="button" title="Ver resumen gráfico del día" aria-label="Ver resumen gráfico del día"><img src="oms-first-choice.png" alt="" aria-hidden="true"></button>';trigger.querySelector('button').addEventListener('click',open);closeButton.addEventListener('click',close);if(location.hash==='#resumen')open();
}
function initializeCutNavToggle(){const nav=document.querySelector('.cut-nav'),label=nav?.querySelector(':scope>span');if(!nav||!label)return;const button=document.createElement('button');button.type='button';button.className='cut-nav-toggle';button.innerHTML='<span>Avance del día</span><i data-lucide="chevron-up"></i>';button.setAttribute('aria-label','Ocultar turnos');button.setAttribute('aria-expanded','true');label.replaceWith(button);const paint=collapsed=>{document.body.classList.toggle('cut-nav-collapsed',collapsed);button.setAttribute('aria-expanded',String(!collapsed));button.setAttribute('aria-label',collapsed?'Mostrar turnos':'Ocultar turnos');button.querySelector('span').textContent=collapsed?'Mostrar turnos':'Avance del día';button.querySelector('svg,i')?.setAttribute('data-lucide',collapsed?'chevron-down':'chevron-up');window.lucide?.createIcons();localStorage.setItem('dhl-turnos-colapsados',String(collapsed))};button.addEventListener('click',()=>paint(!document.body.classList.contains('cut-nav-collapsed')));paint(localStorage.getItem('dhl-turnos-colapsados')==='true')}
function initializeCarouselMode(){
  const button=document.querySelector('#carouselMode');if(!button)return;const areas=['recepcion','preparacion','despacho'],delay=8000;let timer=null,step=0;
  const show=current=>{if(current===0){document.body.classList.remove('summary-open');history.replaceState(null,'',location.pathname+location.search)}else{activeSummaryArea=areas[current-1];renderSummary();document.body.classList.add('summary-open');history.replaceState(null,'','#resumen')}};
  const paint=running=>{document.body.classList.toggle('carousel-running',running);button.setAttribute('aria-pressed',String(running));button.innerHTML=`<i data-lucide="${running?'square':'gallery-horizontal-end'}"></i><span>${running?'Detener':'Carrusel'}</span>`;button.setAttribute('aria-label',running?'Detener modo carrusel':'Iniciar modo carrusel');window.lucide?.createIcons()};
  const stop=()=>{if(timer)clearInterval(timer);timer=null;paint(false)},start=()=>{step=document.body.classList.contains('summary-open')?Math.max(1,areas.indexOf(activeSummaryArea)+1):0;paint(true);timer=setInterval(()=>{step=(step+1)%4;show(step)},delay)};
  button.addEventListener('click',()=>timer?stop():start());document.querySelector('#closeSummary')?.addEventListener('click',stop);paint(false);
}
function initializeCriticalControlIcons(){const card=document.querySelector('.hse-card'),button=card?.querySelector('.hse-view-toggle');if(!button)return;const paint=()=>button.innerHTML=controlIcon(card.classList.contains('show-prevention')?'calendar':'gauge');button.addEventListener('click',()=>queueMicrotask(paint));paint()}
document.querySelector('#clearData').addEventListener('click',()=>{const panel=document.querySelector('#clearAreas'),open=panel.classList.toggle('open');if(!open)closeClearPanel();else panel.setAttribute('aria-hidden','false')});
document.querySelectorAll('[data-clear-area]').forEach(button=>button.addEventListener('click',()=>{selectedClearArea=button.dataset.clearArea;document.querySelector('#selectedClearArea').textContent=`2 · ${areaNames[selectedClearArea]}: ¿qué sección?`;document.querySelector('#clearAreas').classList.add('choose-section')}));
document.querySelectorAll('[data-clear-section]').forEach(button=>button.addEventListener('click',()=>{if(selectedClearArea)clearSection(selectedClearArea,button.dataset.clearSection)}));
document.querySelector('#clearAll').addEventListener('click',clearEverything);
document.querySelector('.clear-back').addEventListener('click',()=>{selectedClearArea=null;document.querySelector('#clearAreas').classList.remove('choose-section')});
document.querySelector('.clear-cancel').addEventListener('click',closeClearPanel);
function addSemanticIcons(){
  const columnIcons=['target','gauge','clock-3','users-round'];document.querySelectorAll('.column-head:not(.blank)').forEach((header,index)=>header.querySelector('b')?.insertAdjacentHTML('afterbegin',`<i data-lucide="${columnIcons[index]}"></i>`));
  const processIcons=['package-open','boxes','truck'];document.querySelectorAll('.process-label').forEach((label,index)=>label.insertAdjacentHTML('afterbegin',`<i class="process-icon" data-lucide="${processIcons[index]}"></i>`));
  document.querySelectorAll('.side-card header h2').forEach(heading=>heading.insertAdjacentHTML('afterbegin',`<i data-lucide="${heading.textContent.includes('QRA')?'clipboard-check':'shield-check'}"></i>`));
  document.querySelectorAll('.data-card h2').forEach(heading=>{const text=heading.textContent.toLowerCase();const icon=text.includes('agenda')?'calendar-check':text.includes('líneas')?'list-checks':text.includes('planificación')?'route':text.includes('variación')?'chart-no-axes-combined':text.includes('horas')?'timer':'users';heading.insertAdjacentHTML('afterbegin',`<i data-lucide="${icon}"></i>`)});
  const side=document.querySelector('.side-panel'),cards=[...side.children];if(cards.length===3)side.replaceChildren(cards[2],cards[0],cards[1]);
}
function init(){initializeAreaMetadata();syncSafetyCounter();syncQraState();initialSnapshot=getSnapshot();activeDate=todayKey();dailyRecord=readDailyRecord();const latest=[...Object.values(dailyRecord.sessions),...Object.values(dailyRecord.drafts)].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt))[0];applySnapshot(blankSnapshot(cuts[0]));renderInlineCrew();loadMeeting(latest?.cut||cuts[0]);paintMeetingStates();addSemanticIcons();initializeBusinessLineSelector();initializeQraRadar();initializeHsePrevention();initializeCriticalControlIcons();initializeSummary();initializeCarouselMode();initializeCutNavToggle();bindDraggableClearPanel();paintSystemDate();window.lucide?.createIcons();setInterval(()=>{checkDayChange();paintSystemDate()},60000)}
init();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
